
package com.hibernatews.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicesImplService", targetNamespace = "http://service.hibernate.com/", wsdlLocation = "http://localhost:8080/TiersAffaires(Oracle)/ServicesImpl?wsdl")
public class ServicesImplService
    extends Service
{

    private final static URL SERVICESIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICESIMPLSERVICE_EXCEPTION;
    private final static QName SERVICESIMPLSERVICE_QNAME = new QName("http://service.hibernate.com/", "ServicesImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TiersAffaires(Oracle)/ServicesImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICESIMPLSERVICE_WSDL_LOCATION = url;
        SERVICESIMPLSERVICE_EXCEPTION = e;
    }

    public ServicesImplService() {
        super(__getWsdlLocation(), SERVICESIMPLSERVICE_QNAME);
    }

    public ServicesImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICESIMPLSERVICE_QNAME, features);
    }

    public ServicesImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICESIMPLSERVICE_QNAME);
    }

    public ServicesImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICESIMPLSERVICE_QNAME, features);
    }

    public ServicesImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicesImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Affaires
     */
    @WebEndpoint(name = "ServicesImplPort")
    public Affaires getServicesImplPort() {
        return super.getPort(new QName("http://service.hibernate.com/", "ServicesImplPort"), Affaires.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Affaires
     */
    @WebEndpoint(name = "ServicesImplPort")
    public Affaires getServicesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.hibernate.com/", "ServicesImplPort"), Affaires.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICESIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICESIMPLSERVICE_EXCEPTION;
        }
        return SERVICESIMPLSERVICE_WSDL_LOCATION;
    }

}
