package com.sofac.models;
// Generated 2 mai 2017 11:47:09 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Affaire generated by hbm2java
 */
@Entity
@Table(name = "AFFAIRE", schema = "OPS$INGENETUDES", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "DOSSIER", "CONTRAT", "AVENANT" }),
		@UniqueConstraint(columnNames = "IE_AFFAIRE") })
public class Affaire implements java.io.Serializable {

	private long idAffaire;
	private int dossier;
	private String contrat;
	private byte avenant;
	private String libelle;
	private Long dateCreation;
	private Long dateModification;
	private String contratType;
	private String codeProduit;
	private String codeCategorieAffaire;
	private String codeReseau;
	private String codeLangue;
	private String codeDevise;
	private String codeReglement;
	private String codeReglementDebours;
	private String codeRegrEnc;
	private String codeResiliation;
	private String codeImposition;
	private String codeTaxe;
	private String codeContentieux;
	private String codeStatut;
	private String codeService;
	private String codeRegroupement;
	private String codeEditionFacture;
	private String codeMethodeSubvention;
	private String codeInfoExterne;
	private String codeMethodeRelance;
	private String codeArreteAssiette;
	private String codeFormuleIr;
	private String codeFormulePen;
	private String tiersSociete;
	private String tiersClient;
	private String tiersProspect;
	private String tiersDelegation;
	private String tiersCdf;
	private String tiersRacheteur;
	private String tiersReprise;
	private String tiersGestionnaire;
	private String flagPool;
	private Byte noPool;
	private Byte noAdresse;
	private Byte noRib;
	private Byte dureeMois;
	private Byte dureeAns;
	private Byte dureeJours;
	private Long dateEngagement;
	private Long dateSignature;
	private Long dateFin;
	private Long dateMel;
	private Long dateMelPrevisionnelle;
	private Long dateArretFacturation;
	private Long dateResiliation;
	private Long dateLeveeOption1;
	private Long dateDebAvt;
	private Long dateFinAvt;
	private Long dateDebPrel;
	private Byte periodeLeveeOption;
	private Byte nbMoisPreavis;
	private BigDecimal mtInvest;
	private String noEngagement;
	private BigDecimal engagementSignature;
	private BigDecimal engagementInitial;
	private BigDecimal plafondDecaissement;
	private BigDecimal montantPenalisation;
	private BigDecimal montantDepotGarantie;
	private BigDecimal montantTtc;
	private BigDecimal pourcDepotGarantie;
	private BigDecimal montantSubvention;
	private BigDecimal montantVrHt;
	private BigDecimal pourcentageVrHt;
	private Long noSimulation;
	private BigDecimal tauxActuariel;
	private BigDecimal tegm;
	private String codeExigibilite;
	private Byte nbMoisExigibilite;
	private Byte nbJoursExigibilite;
	private Byte ecartFactureM;
	private Byte ecartFactureJ;
	private String flagVerrou;
	private String flagRemDepotGarantie;
	private String affectationAnalytique;
	private Short nbImpayes;
	private Short nbIncidents;
	private String referenceExterne;
	private BigDecimal tri;
	private String typeOrdreAffect;
	private String ieAffaire;
	private String codeFormuleRep;
	private Long idEngaglign;
	private Long idImmeuble;
	private String codeTypeBail;
	private Long dateContentieux;
	private String codeTypeMel;
	private Long dateCommande;
	private String tiersProprietaire;
	private Long idDosadm;
	private String codeProtection;
	private String noClassement;
	private String codeStatutImpose;
	private String codeStatutCompta;
	private Long datePriseEnCharge;
	private String codeModeleReleve;
	private Long idChangeDevrDeva;
	private String codeOffre;
	private BigDecimal tauxRecuperation;
	private Byte nbJoursScrivener;
	private Long dateExpScrivener;
	private String codeRegionInt;
	private String codeSecteur;
	private String codeNeiertz;
	private String codeTrtFacturation;
	private Short nbMaxIncidents;
	private String codeStatutRisque;
	private String flagConversion;
	private String codeDeviseAvtEuro;
	private String indicateurConversion;
	private BigDecimal numAvtEuro;
	private BigDecimal denoAvtEuro;
	private String flagTranche;
	private Long idConcadre;
	private String codeBallon;
	private BigDecimal pourcentageRor;
	private String codeTauxSuspension;
	private String codeTitrisation;
	private Long idAffaireGlb;
	private String flagAffaireGlb;
	private String flagGlbFacture;
	private String codeTypeDuree;
	private String codeCalcArrete;
	private Long maIdAffaireSub;
	private String codeTtas;
	private Integer asnefNumber;
	private String codeRestructuration;
	private Long noPartition;
	private Long idAffaireRenouvelee;
	private String refCommerciale;
	private Long idGroupeSgt;
	private Long idGrpaffarc;
	private String codeForcageIeAff;

	public Affaire() {
	}

	public Affaire(long idAffaire, int dossier, String contrat, byte avenant, String ieAffaire) {
		this.idAffaire = idAffaire;
		this.dossier = dossier;
		this.contrat = contrat;
		this.avenant = avenant;
		this.ieAffaire = ieAffaire;
	}

	public Affaire(long idAffaire, int dossier, String contrat, byte avenant, String libelle, Long dateCreation,
			Long dateModification, String contratType, String codeProduit, String codeCategorieAffaire,
			String codeReseau, String codeLangue, String codeDevise, String codeReglement, String codeReglementDebours,
			String codeRegrEnc, String codeResiliation, String codeImposition, String codeTaxe, String codeContentieux,
			String codeStatut, String codeService, String codeRegroupement, String codeEditionFacture,
			String codeMethodeSubvention, String codeInfoExterne, String codeMethodeRelance, String codeArreteAssiette,
			String codeFormuleIr, String codeFormulePen, String tiersSociete, String tiersClient, String tiersProspect,
			String tiersDelegation, String tiersCdf, String tiersRacheteur, String tiersReprise,
			String tiersGestionnaire, String flagPool, Byte noPool, Byte noAdresse, Byte noRib, Byte dureeMois,
			Byte dureeAns, Byte dureeJours, Long dateEngagement, Long dateSignature, Long dateFin, Long dateMel,
			Long dateMelPrevisionnelle, Long dateArretFacturation, Long dateResiliation, Long dateLeveeOption1,
			Long dateDebAvt, Long dateFinAvt, Long dateDebPrel, Byte periodeLeveeOption, Byte nbMoisPreavis,
			BigDecimal mtInvest, String noEngagement, BigDecimal engagementSignature, BigDecimal engagementInitial,
			BigDecimal plafondDecaissement, BigDecimal montantPenalisation, BigDecimal montantDepotGarantie,
			BigDecimal montantTtc, BigDecimal pourcDepotGarantie, BigDecimal montantSubvention, BigDecimal montantVrHt,
			BigDecimal pourcentageVrHt, Long noSimulation, BigDecimal tauxActuariel, BigDecimal tegm,
			String codeExigibilite, Byte nbMoisExigibilite, Byte nbJoursExigibilite, Byte ecartFactureM,
			Byte ecartFactureJ, String flagVerrou, String flagRemDepotGarantie, String affectationAnalytique,
			Short nbImpayes, Short nbIncidents, String referenceExterne, BigDecimal tri, String typeOrdreAffect,
			String ieAffaire, String codeFormuleRep, Long idEngaglign, Long idImmeuble, String codeTypeBail,
			Long dateContentieux, String codeTypeMel, Long dateCommande, String tiersProprietaire, Long idDosadm,
			String codeProtection, String noClassement, String codeStatutImpose, String codeStatutCompta,
			Long datePriseEnCharge, String codeModeleReleve, Long idChangeDevrDeva, String codeOffre,
			BigDecimal tauxRecuperation, Byte nbJoursScrivener, Long dateExpScrivener, String codeRegionInt,
			String codeSecteur, String codeNeiertz, String codeTrtFacturation, Short nbMaxIncidents,
			String codeStatutRisque, String flagConversion, String codeDeviseAvtEuro, String indicateurConversion,
			BigDecimal numAvtEuro, BigDecimal denoAvtEuro, String flagTranche, Long idConcadre, String codeBallon,
			BigDecimal pourcentageRor, String codeTauxSuspension, String codeTitrisation, Long idAffaireGlb,
			String flagAffaireGlb, String flagGlbFacture, String codeTypeDuree, String codeCalcArrete,
			Long maIdAffaireSub, String codeTtas, Integer asnefNumber, String codeRestructuration, Long noPartition,
			Long idAffaireRenouvelee, String refCommerciale, Long idGroupeSgt, Long idGrpaffarc,
			String codeForcageIeAff) {
		this.idAffaire = idAffaire;
		this.dossier = dossier;
		this.contrat = contrat;
		this.avenant = avenant;
		this.libelle = libelle;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.contratType = contratType;
		this.codeProduit = codeProduit;
		this.codeCategorieAffaire = codeCategorieAffaire;
		this.codeReseau = codeReseau;
		this.codeLangue = codeLangue;
		this.codeDevise = codeDevise;
		this.codeReglement = codeReglement;
		this.codeReglementDebours = codeReglementDebours;
		this.codeRegrEnc = codeRegrEnc;
		this.codeResiliation = codeResiliation;
		this.codeImposition = codeImposition;
		this.codeTaxe = codeTaxe;
		this.codeContentieux = codeContentieux;
		this.codeStatut = codeStatut;
		this.codeService = codeService;
		this.codeRegroupement = codeRegroupement;
		this.codeEditionFacture = codeEditionFacture;
		this.codeMethodeSubvention = codeMethodeSubvention;
		this.codeInfoExterne = codeInfoExterne;
		this.codeMethodeRelance = codeMethodeRelance;
		this.codeArreteAssiette = codeArreteAssiette;
		this.codeFormuleIr = codeFormuleIr;
		this.codeFormulePen = codeFormulePen;
		this.tiersSociete = tiersSociete;
		this.tiersClient = tiersClient;
		this.tiersProspect = tiersProspect;
		this.tiersDelegation = tiersDelegation;
		this.tiersCdf = tiersCdf;
		this.tiersRacheteur = tiersRacheteur;
		this.tiersReprise = tiersReprise;
		this.tiersGestionnaire = tiersGestionnaire;
		this.flagPool = flagPool;
		this.noPool = noPool;
		this.noAdresse = noAdresse;
		this.noRib = noRib;
		this.dureeMois = dureeMois;
		this.dureeAns = dureeAns;
		this.dureeJours = dureeJours;
		this.dateEngagement = dateEngagement;
		this.dateSignature = dateSignature;
		this.dateFin = dateFin;
		this.dateMel = dateMel;
		this.dateMelPrevisionnelle = dateMelPrevisionnelle;
		this.dateArretFacturation = dateArretFacturation;
		this.dateResiliation = dateResiliation;
		this.dateLeveeOption1 = dateLeveeOption1;
		this.dateDebAvt = dateDebAvt;
		this.dateFinAvt = dateFinAvt;
		this.dateDebPrel = dateDebPrel;
		this.periodeLeveeOption = periodeLeveeOption;
		this.nbMoisPreavis = nbMoisPreavis;
		this.mtInvest = mtInvest;
		this.noEngagement = noEngagement;
		this.engagementSignature = engagementSignature;
		this.engagementInitial = engagementInitial;
		this.plafondDecaissement = plafondDecaissement;
		this.montantPenalisation = montantPenalisation;
		this.montantDepotGarantie = montantDepotGarantie;
		this.montantTtc = montantTtc;
		this.pourcDepotGarantie = pourcDepotGarantie;
		this.montantSubvention = montantSubvention;
		this.montantVrHt = montantVrHt;
		this.pourcentageVrHt = pourcentageVrHt;
		this.noSimulation = noSimulation;
		this.tauxActuariel = tauxActuariel;
		this.tegm = tegm;
		this.codeExigibilite = codeExigibilite;
		this.nbMoisExigibilite = nbMoisExigibilite;
		this.nbJoursExigibilite = nbJoursExigibilite;
		this.ecartFactureM = ecartFactureM;
		this.ecartFactureJ = ecartFactureJ;
		this.flagVerrou = flagVerrou;
		this.flagRemDepotGarantie = flagRemDepotGarantie;
		this.affectationAnalytique = affectationAnalytique;
		this.nbImpayes = nbImpayes;
		this.nbIncidents = nbIncidents;
		this.referenceExterne = referenceExterne;
		this.tri = tri;
		this.typeOrdreAffect = typeOrdreAffect;
		this.ieAffaire = ieAffaire;
		this.codeFormuleRep = codeFormuleRep;
		this.idEngaglign = idEngaglign;
		this.idImmeuble = idImmeuble;
		this.codeTypeBail = codeTypeBail;
		this.dateContentieux = dateContentieux;
		this.codeTypeMel = codeTypeMel;
		this.dateCommande = dateCommande;
		this.tiersProprietaire = tiersProprietaire;
		this.idDosadm = idDosadm;
		this.codeProtection = codeProtection;
		this.noClassement = noClassement;
		this.codeStatutImpose = codeStatutImpose;
		this.codeStatutCompta = codeStatutCompta;
		this.datePriseEnCharge = datePriseEnCharge;
		this.codeModeleReleve = codeModeleReleve;
		this.idChangeDevrDeva = idChangeDevrDeva;
		this.codeOffre = codeOffre;
		this.tauxRecuperation = tauxRecuperation;
		this.nbJoursScrivener = nbJoursScrivener;
		this.dateExpScrivener = dateExpScrivener;
		this.codeRegionInt = codeRegionInt;
		this.codeSecteur = codeSecteur;
		this.codeNeiertz = codeNeiertz;
		this.codeTrtFacturation = codeTrtFacturation;
		this.nbMaxIncidents = nbMaxIncidents;
		this.codeStatutRisque = codeStatutRisque;
		this.flagConversion = flagConversion;
		this.codeDeviseAvtEuro = codeDeviseAvtEuro;
		this.indicateurConversion = indicateurConversion;
		this.numAvtEuro = numAvtEuro;
		this.denoAvtEuro = denoAvtEuro;
		this.flagTranche = flagTranche;
		this.idConcadre = idConcadre;
		this.codeBallon = codeBallon;
		this.pourcentageRor = pourcentageRor;
		this.codeTauxSuspension = codeTauxSuspension;
		this.codeTitrisation = codeTitrisation;
		this.idAffaireGlb = idAffaireGlb;
		this.flagAffaireGlb = flagAffaireGlb;
		this.flagGlbFacture = flagGlbFacture;
		this.codeTypeDuree = codeTypeDuree;
		this.codeCalcArrete = codeCalcArrete;
		this.maIdAffaireSub = maIdAffaireSub;
		this.codeTtas = codeTtas;
		this.asnefNumber = asnefNumber;
		this.codeRestructuration = codeRestructuration;
		this.noPartition = noPartition;
		this.idAffaireRenouvelee = idAffaireRenouvelee;
		this.refCommerciale = refCommerciale;
		this.idGroupeSgt = idGroupeSgt;
		this.idGrpaffarc = idGrpaffarc;
		this.codeForcageIeAff = codeForcageIeAff;
	}

	@Id

	@Column(name = "ID_AFFAIRE", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdAffaire() {
		return this.idAffaire;
	}

	public void setIdAffaire(long idAffaire) {
		this.idAffaire = idAffaire;
	}

	@Column(name = "DOSSIER", nullable = false, precision = 6, scale = 0)
	public int getDossier() {
		return this.dossier;
	}

	public void setDossier(int dossier) {
		this.dossier = dossier;
	}

	@Column(name = "CONTRAT", nullable = false, length = 2)
	public String getContrat() {
		return this.contrat;
	}

	public void setContrat(String contrat) {
		this.contrat = contrat;
	}

	@Column(name = "AVENANT", nullable = false, precision = 2, scale = 0)
	public byte getAvenant() {
		return this.avenant;
	}

	public void setAvenant(byte avenant) {
		this.avenant = avenant;
	}

	@Column(name = "LIBELLE", length = 30)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "DATE_CREATION", precision = 10, scale = 0)
	public Long getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Long dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "DATE_MODIFICATION", precision = 10, scale = 0)
	public Long getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(Long dateModification) {
		this.dateModification = dateModification;
	}

	@Column(name = "CONTRAT_TYPE", length = 10)
	public String getContratType() {
		return this.contratType;
	}

	public void setContratType(String contratType) {
		this.contratType = contratType;
	}

	@Column(name = "CODE_PRODUIT", length = 4)
	public String getCodeProduit() {
		return this.codeProduit;
	}

	public void setCodeProduit(String codeProduit) {
		this.codeProduit = codeProduit;
	}

	@Column(name = "CODE_CATEGORIE_AFFAIRE", length = 4)
	public String getCodeCategorieAffaire() {
		return this.codeCategorieAffaire;
	}

	public void setCodeCategorieAffaire(String codeCategorieAffaire) {
		this.codeCategorieAffaire = codeCategorieAffaire;
	}

	@Column(name = "CODE_RESEAU", length = 4)
	public String getCodeReseau() {
		return this.codeReseau;
	}

	public void setCodeReseau(String codeReseau) {
		this.codeReseau = codeReseau;
	}

	@Column(name = "CODE_LANGUE", length = 4)
	public String getCodeLangue() {
		return this.codeLangue;
	}

	public void setCodeLangue(String codeLangue) {
		this.codeLangue = codeLangue;
	}

	@Column(name = "CODE_DEVISE", length = 4)
	public String getCodeDevise() {
		return this.codeDevise;
	}

	public void setCodeDevise(String codeDevise) {
		this.codeDevise = codeDevise;
	}

	@Column(name = "CODE_REGLEMENT", length = 4)
	public String getCodeReglement() {
		return this.codeReglement;
	}

	public void setCodeReglement(String codeReglement) {
		this.codeReglement = codeReglement;
	}

	@Column(name = "CODE_REGLEMENT_DEBOURS", length = 4)
	public String getCodeReglementDebours() {
		return this.codeReglementDebours;
	}

	public void setCodeReglementDebours(String codeReglementDebours) {
		this.codeReglementDebours = codeReglementDebours;
	}

	@Column(name = "CODE_REGR_ENC", length = 4)
	public String getCodeRegrEnc() {
		return this.codeRegrEnc;
	}

	public void setCodeRegrEnc(String codeRegrEnc) {
		this.codeRegrEnc = codeRegrEnc;
	}

	@Column(name = "CODE_RESILIATION", length = 4)
	public String getCodeResiliation() {
		return this.codeResiliation;
	}

	public void setCodeResiliation(String codeResiliation) {
		this.codeResiliation = codeResiliation;
	}

	@Column(name = "CODE_IMPOSITION", length = 4)
	public String getCodeImposition() {
		return this.codeImposition;
	}

	public void setCodeImposition(String codeImposition) {
		this.codeImposition = codeImposition;
	}

	@Column(name = "CODE_TAXE", length = 4)
	public String getCodeTaxe() {
		return this.codeTaxe;
	}

	public void setCodeTaxe(String codeTaxe) {
		this.codeTaxe = codeTaxe;
	}

	@Column(name = "CODE_CONTENTIEUX", length = 4)
	public String getCodeContentieux() {
		return this.codeContentieux;
	}

	public void setCodeContentieux(String codeContentieux) {
		this.codeContentieux = codeContentieux;
	}

	@Column(name = "CODE_STATUT", length = 4)
	public String getCodeStatut() {
		return this.codeStatut;
	}

	public void setCodeStatut(String codeStatut) {
		this.codeStatut = codeStatut;
	}

	@Column(name = "CODE_SERVICE", length = 4)
	public String getCodeService() {
		return this.codeService;
	}

	public void setCodeService(String codeService) {
		this.codeService = codeService;
	}

	@Column(name = "CODE_REGROUPEMENT", length = 4)
	public String getCodeRegroupement() {
		return this.codeRegroupement;
	}

	public void setCodeRegroupement(String codeRegroupement) {
		this.codeRegroupement = codeRegroupement;
	}

	@Column(name = "CODE_EDITION_FACTURE", length = 4)
	public String getCodeEditionFacture() {
		return this.codeEditionFacture;
	}

	public void setCodeEditionFacture(String codeEditionFacture) {
		this.codeEditionFacture = codeEditionFacture;
	}

	@Column(name = "CODE_METHODE_SUBVENTION", length = 4)
	public String getCodeMethodeSubvention() {
		return this.codeMethodeSubvention;
	}

	public void setCodeMethodeSubvention(String codeMethodeSubvention) {
		this.codeMethodeSubvention = codeMethodeSubvention;
	}

	@Column(name = "CODE_INFO_EXTERNE", length = 4)
	public String getCodeInfoExterne() {
		return this.codeInfoExterne;
	}

	public void setCodeInfoExterne(String codeInfoExterne) {
		this.codeInfoExterne = codeInfoExterne;
	}

	@Column(name = "CODE_METHODE_RELANCE", length = 4)
	public String getCodeMethodeRelance() {
		return this.codeMethodeRelance;
	}

	public void setCodeMethodeRelance(String codeMethodeRelance) {
		this.codeMethodeRelance = codeMethodeRelance;
	}

	@Column(name = "CODE_ARRETE_ASSIETTE", length = 4)
	public String getCodeArreteAssiette() {
		return this.codeArreteAssiette;
	}

	public void setCodeArreteAssiette(String codeArreteAssiette) {
		this.codeArreteAssiette = codeArreteAssiette;
	}

	@Column(name = "CODE_FORMULE_IR", length = 4)
	public String getCodeFormuleIr() {
		return this.codeFormuleIr;
	}

	public void setCodeFormuleIr(String codeFormuleIr) {
		this.codeFormuleIr = codeFormuleIr;
	}

	@Column(name = "CODE_FORMULE_PEN", length = 4)
	public String getCodeFormulePen() {
		return this.codeFormulePen;
	}

	public void setCodeFormulePen(String codeFormulePen) {
		this.codeFormulePen = codeFormulePen;
	}

	@Column(name = "TIERS_SOCIETE", length = 10)
	public String getTiersSociete() {
		return this.tiersSociete;
	}

	public void setTiersSociete(String tiersSociete) {
		this.tiersSociete = tiersSociete;
	}

	@Column(name = "TIERS_CLIENT", length = 10)
	public String getTiersClient() {
		return this.tiersClient;
	}

	public void setTiersClient(String tiersClient) {
		this.tiersClient = tiersClient;
	}

	@Column(name = "TIERS_PROSPECT", length = 10)
	public String getTiersProspect() {
		return this.tiersProspect;
	}

	public void setTiersProspect(String tiersProspect) {
		this.tiersProspect = tiersProspect;
	}

	@Column(name = "TIERS_DELEGATION", length = 10)
	public String getTiersDelegation() {
		return this.tiersDelegation;
	}

	public void setTiersDelegation(String tiersDelegation) {
		this.tiersDelegation = tiersDelegation;
	}

	@Column(name = "TIERS_CDF", length = 10)
	public String getTiersCdf() {
		return this.tiersCdf;
	}

	public void setTiersCdf(String tiersCdf) {
		this.tiersCdf = tiersCdf;
	}

	@Column(name = "TIERS_RACHETEUR", length = 10)
	public String getTiersRacheteur() {
		return this.tiersRacheteur;
	}

	public void setTiersRacheteur(String tiersRacheteur) {
		this.tiersRacheteur = tiersRacheteur;
	}

	@Column(name = "TIERS_REPRISE", length = 10)
	public String getTiersReprise() {
		return this.tiersReprise;
	}

	public void setTiersReprise(String tiersReprise) {
		this.tiersReprise = tiersReprise;
	}

	@Column(name = "TIERS_GESTIONNAIRE", length = 10)
	public String getTiersGestionnaire() {
		return this.tiersGestionnaire;
	}

	public void setTiersGestionnaire(String tiersGestionnaire) {
		this.tiersGestionnaire = tiersGestionnaire;
	}

	@Column(name = "FLAG_POOL", length = 1)
	public String getFlagPool() {
		return this.flagPool;
	}

	public void setFlagPool(String flagPool) {
		this.flagPool = flagPool;
	}

	@Column(name = "NO_POOL", precision = 2, scale = 0)
	public Byte getNoPool() {
		return this.noPool;
	}

	public void setNoPool(Byte noPool) {
		this.noPool = noPool;
	}

	@Column(name = "NO_ADRESSE", precision = 2, scale = 0)
	public Byte getNoAdresse() {
		return this.noAdresse;
	}

	public void setNoAdresse(Byte noAdresse) {
		this.noAdresse = noAdresse;
	}

	@Column(name = "NO_RIB", precision = 2, scale = 0)
	public Byte getNoRib() {
		return this.noRib;
	}

	public void setNoRib(Byte noRib) {
		this.noRib = noRib;
	}

	@Column(name = "DUREE_MOIS", precision = 2, scale = 0)
	public Byte getDureeMois() {
		return this.dureeMois;
	}

	public void setDureeMois(Byte dureeMois) {
		this.dureeMois = dureeMois;
	}

	@Column(name = "DUREE_ANS", precision = 2, scale = 0)
	public Byte getDureeAns() {
		return this.dureeAns;
	}

	public void setDureeAns(Byte dureeAns) {
		this.dureeAns = dureeAns;
	}

	@Column(name = "DUREE_JOURS", precision = 2, scale = 0)
	public Byte getDureeJours() {
		return this.dureeJours;
	}

	public void setDureeJours(Byte dureeJours) {
		this.dureeJours = dureeJours;
	}

	@Column(name = "DATE_ENGAGEMENT", precision = 10, scale = 0)
	public Long getDateEngagement() {
		return this.dateEngagement;
	}

	public void setDateEngagement(Long dateEngagement) {
		this.dateEngagement = dateEngagement;
	}

	@Column(name = "DATE_SIGNATURE", precision = 10, scale = 0)
	public Long getDateSignature() {
		return this.dateSignature;
	}

	public void setDateSignature(Long dateSignature) {
		this.dateSignature = dateSignature;
	}

	@Column(name = "DATE_FIN", precision = 10, scale = 0)
	public Long getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Long dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "DATE_MEL", precision = 10, scale = 0)
	public Long getDateMel() {
		return this.dateMel;
	}

	public void setDateMel(Long dateMel) {
		this.dateMel = dateMel;
	}

	@Column(name = "DATE_MEL_PREVISIONNELLE", precision = 10, scale = 0)
	public Long getDateMelPrevisionnelle() {
		return this.dateMelPrevisionnelle;
	}

	public void setDateMelPrevisionnelle(Long dateMelPrevisionnelle) {
		this.dateMelPrevisionnelle = dateMelPrevisionnelle;
	}

	@Column(name = "DATE_ARRET_FACTURATION", precision = 10, scale = 0)
	public Long getDateArretFacturation() {
		return this.dateArretFacturation;
	}

	public void setDateArretFacturation(Long dateArretFacturation) {
		this.dateArretFacturation = dateArretFacturation;
	}

	@Column(name = "DATE_RESILIATION", precision = 10, scale = 0)
	public Long getDateResiliation() {
		return this.dateResiliation;
	}

	public void setDateResiliation(Long dateResiliation) {
		this.dateResiliation = dateResiliation;
	}

	@Column(name = "DATE_LEVEE_OPTION_1", precision = 10, scale = 0)
	public Long getDateLeveeOption1() {
		return this.dateLeveeOption1;
	}

	public void setDateLeveeOption1(Long dateLeveeOption1) {
		this.dateLeveeOption1 = dateLeveeOption1;
	}

	@Column(name = "DATE_DEB_AVT", precision = 10, scale = 0)
	public Long getDateDebAvt() {
		return this.dateDebAvt;
	}

	public void setDateDebAvt(Long dateDebAvt) {
		this.dateDebAvt = dateDebAvt;
	}

	@Column(name = "DATE_FIN_AVT", precision = 10, scale = 0)
	public Long getDateFinAvt() {
		return this.dateFinAvt;
	}

	public void setDateFinAvt(Long dateFinAvt) {
		this.dateFinAvt = dateFinAvt;
	}

	@Column(name = "DATE_DEB_PREL", precision = 10, scale = 0)
	public Long getDateDebPrel() {
		return this.dateDebPrel;
	}

	public void setDateDebPrel(Long dateDebPrel) {
		this.dateDebPrel = dateDebPrel;
	}

	@Column(name = "PERIODE_LEVEE_OPTION", precision = 2, scale = 0)
	public Byte getPeriodeLeveeOption() {
		return this.periodeLeveeOption;
	}

	public void setPeriodeLeveeOption(Byte periodeLeveeOption) {
		this.periodeLeveeOption = periodeLeveeOption;
	}

	@Column(name = "NB_MOIS_PREAVIS", precision = 2, scale = 0)
	public Byte getNbMoisPreavis() {
		return this.nbMoisPreavis;
	}

	public void setNbMoisPreavis(Byte nbMoisPreavis) {
		this.nbMoisPreavis = nbMoisPreavis;
	}

	@Column(name = "MT_INVEST", precision = 18, scale = 3)
	public BigDecimal getMtInvest() {
		return this.mtInvest;
	}

	public void setMtInvest(BigDecimal mtInvest) {
		this.mtInvest = mtInvest;
	}

	@Column(name = "NO_ENGAGEMENT", length = 10)
	public String getNoEngagement() {
		return this.noEngagement;
	}

	public void setNoEngagement(String noEngagement) {
		this.noEngagement = noEngagement;
	}

	@Column(name = "ENGAGEMENT_SIGNATURE", precision = 18, scale = 3)
	public BigDecimal getEngagementSignature() {
		return this.engagementSignature;
	}

	public void setEngagementSignature(BigDecimal engagementSignature) {
		this.engagementSignature = engagementSignature;
	}

	@Column(name = "ENGAGEMENT_INITIAL", precision = 18, scale = 3)
	public BigDecimal getEngagementInitial() {
		return this.engagementInitial;
	}

	public void setEngagementInitial(BigDecimal engagementInitial) {
		this.engagementInitial = engagementInitial;
	}

	@Column(name = "PLAFOND_DECAISSEMENT", precision = 18, scale = 3)
	public BigDecimal getPlafondDecaissement() {
		return this.plafondDecaissement;
	}

	public void setPlafondDecaissement(BigDecimal plafondDecaissement) {
		this.plafondDecaissement = plafondDecaissement;
	}

	@Column(name = "MONTANT_PENALISATION", precision = 18, scale = 3)
	public BigDecimal getMontantPenalisation() {
		return this.montantPenalisation;
	}

	public void setMontantPenalisation(BigDecimal montantPenalisation) {
		this.montantPenalisation = montantPenalisation;
	}

	@Column(name = "MONTANT_DEPOT_GARANTIE", precision = 18, scale = 3)
	public BigDecimal getMontantDepotGarantie() {
		return this.montantDepotGarantie;
	}

	public void setMontantDepotGarantie(BigDecimal montantDepotGarantie) {
		this.montantDepotGarantie = montantDepotGarantie;
	}

	@Column(name = "MONTANT_TTC", precision = 18, scale = 3)
	public BigDecimal getMontantTtc() {
		return this.montantTtc;
	}

	public void setMontantTtc(BigDecimal montantTtc) {
		this.montantTtc = montantTtc;
	}

	@Column(name = "POURC_DEPOT_GARANTIE", precision = 11, scale = 6)
	public BigDecimal getPourcDepotGarantie() {
		return this.pourcDepotGarantie;
	}

	public void setPourcDepotGarantie(BigDecimal pourcDepotGarantie) {
		this.pourcDepotGarantie = pourcDepotGarantie;
	}

	@Column(name = "MONTANT_SUBVENTION", precision = 18, scale = 3)
	public BigDecimal getMontantSubvention() {
		return this.montantSubvention;
	}

	public void setMontantSubvention(BigDecimal montantSubvention) {
		this.montantSubvention = montantSubvention;
	}

	@Column(name = "MONTANT_VR_HT", precision = 18, scale = 3)
	public BigDecimal getMontantVrHt() {
		return this.montantVrHt;
	}

	public void setMontantVrHt(BigDecimal montantVrHt) {
		this.montantVrHt = montantVrHt;
	}

	@Column(name = "POURCENTAGE_VR_HT", precision = 11, scale = 6)
	public BigDecimal getPourcentageVrHt() {
		return this.pourcentageVrHt;
	}

	public void setPourcentageVrHt(BigDecimal pourcentageVrHt) {
		this.pourcentageVrHt = pourcentageVrHt;
	}

	@Column(name = "NO_SIMULATION", precision = 10, scale = 0)
	public Long getNoSimulation() {
		return this.noSimulation;
	}

	public void setNoSimulation(Long noSimulation) {
		this.noSimulation = noSimulation;
	}

	@Column(name = "TAUX_ACTUARIEL", precision = 11, scale = 6)
	public BigDecimal getTauxActuariel() {
		return this.tauxActuariel;
	}

	public void setTauxActuariel(BigDecimal tauxActuariel) {
		this.tauxActuariel = tauxActuariel;
	}

	@Column(name = "TEGM", precision = 11, scale = 6)
	public BigDecimal getTegm() {
		return this.tegm;
	}

	public void setTegm(BigDecimal tegm) {
		this.tegm = tegm;
	}

	@Column(name = "CODE_EXIGIBILITE", length = 4)
	public String getCodeExigibilite() {
		return this.codeExigibilite;
	}

	public void setCodeExigibilite(String codeExigibilite) {
		this.codeExigibilite = codeExigibilite;
	}

	@Column(name = "NB_MOIS_EXIGIBILITE", precision = 2, scale = 0)
	public Byte getNbMoisExigibilite() {
		return this.nbMoisExigibilite;
	}

	public void setNbMoisExigibilite(Byte nbMoisExigibilite) {
		this.nbMoisExigibilite = nbMoisExigibilite;
	}

	@Column(name = "NB_JOURS_EXIGIBILITE", precision = 2, scale = 0)
	public Byte getNbJoursExigibilite() {
		return this.nbJoursExigibilite;
	}

	public void setNbJoursExigibilite(Byte nbJoursExigibilite) {
		this.nbJoursExigibilite = nbJoursExigibilite;
	}

	@Column(name = "ECART_FACTURE_M", precision = 2, scale = 0)
	public Byte getEcartFactureM() {
		return this.ecartFactureM;
	}

	public void setEcartFactureM(Byte ecartFactureM) {
		this.ecartFactureM = ecartFactureM;
	}

	@Column(name = "ECART_FACTURE_J", precision = 2, scale = 0)
	public Byte getEcartFactureJ() {
		return this.ecartFactureJ;
	}

	public void setEcartFactureJ(Byte ecartFactureJ) {
		this.ecartFactureJ = ecartFactureJ;
	}

	@Column(name = "FLAG_VERROU", length = 1)
	public String getFlagVerrou() {
		return this.flagVerrou;
	}

	public void setFlagVerrou(String flagVerrou) {
		this.flagVerrou = flagVerrou;
	}

	@Column(name = "FLAG_REM_DEPOT_GARANTIE", length = 1)
	public String getFlagRemDepotGarantie() {
		return this.flagRemDepotGarantie;
	}

	public void setFlagRemDepotGarantie(String flagRemDepotGarantie) {
		this.flagRemDepotGarantie = flagRemDepotGarantie;
	}

	@Column(name = "AFFECTATION_ANALYTIQUE", length = 10)
	public String getAffectationAnalytique() {
		return this.affectationAnalytique;
	}

	public void setAffectationAnalytique(String affectationAnalytique) {
		this.affectationAnalytique = affectationAnalytique;
	}

	@Column(name = "NB_IMPAYES", precision = 3, scale = 0)
	public Short getNbImpayes() {
		return this.nbImpayes;
	}

	public void setNbImpayes(Short nbImpayes) {
		this.nbImpayes = nbImpayes;
	}

	@Column(name = "NB_INCIDENTS", precision = 3, scale = 0)
	public Short getNbIncidents() {
		return this.nbIncidents;
	}

	public void setNbIncidents(Short nbIncidents) {
		this.nbIncidents = nbIncidents;
	}

	@Column(name = "REFERENCE_EXTERNE", length = 30)
	public String getReferenceExterne() {
		return this.referenceExterne;
	}

	public void setReferenceExterne(String referenceExterne) {
		this.referenceExterne = referenceExterne;
	}

	@Column(name = "TRI", precision = 11, scale = 6)
	public BigDecimal getTri() {
		return this.tri;
	}

	public void setTri(BigDecimal tri) {
		this.tri = tri;
	}

	@Column(name = "TYPE_ORDRE_AFFECT", length = 10)
	public String getTypeOrdreAffect() {
		return this.typeOrdreAffect;
	}

	public void setTypeOrdreAffect(String typeOrdreAffect) {
		this.typeOrdreAffect = typeOrdreAffect;
	}

	@Column(name = "IE_AFFAIRE", unique = true, nullable = false, length = 12)
	public String getIeAffaire() {
		return this.ieAffaire;
	}

	public void setIeAffaire(String ieAffaire) {
		this.ieAffaire = ieAffaire;
	}

	@Column(name = "CODE_FORMULE_REP", length = 4)
	public String getCodeFormuleRep() {
		return this.codeFormuleRep;
	}

	public void setCodeFormuleRep(String codeFormuleRep) {
		this.codeFormuleRep = codeFormuleRep;
	}

	@Column(name = "ID_ENGAGLIGN", precision = 10, scale = 0)
	public Long getIdEngaglign() {
		return this.idEngaglign;
	}

	public void setIdEngaglign(Long idEngaglign) {
		this.idEngaglign = idEngaglign;
	}

	@Column(name = "ID_IMMEUBLE", precision = 10, scale = 0)
	public Long getIdImmeuble() {
		return this.idImmeuble;
	}

	public void setIdImmeuble(Long idImmeuble) {
		this.idImmeuble = idImmeuble;
	}

	@Column(name = "CODE_TYPE_BAIL", length = 4)
	public String getCodeTypeBail() {
		return this.codeTypeBail;
	}

	public void setCodeTypeBail(String codeTypeBail) {
		this.codeTypeBail = codeTypeBail;
	}

	@Column(name = "DATE_CONTENTIEUX", precision = 10, scale = 0)
	public Long getDateContentieux() {
		return this.dateContentieux;
	}

	public void setDateContentieux(Long dateContentieux) {
		this.dateContentieux = dateContentieux;
	}

	@Column(name = "CODE_TYPE_MEL", length = 4)
	public String getCodeTypeMel() {
		return this.codeTypeMel;
	}

	public void setCodeTypeMel(String codeTypeMel) {
		this.codeTypeMel = codeTypeMel;
	}

	@Column(name = "DATE_COMMANDE", precision = 10, scale = 0)
	public Long getDateCommande() {
		return this.dateCommande;
	}

	public void setDateCommande(Long dateCommande) {
		this.dateCommande = dateCommande;
	}

	@Column(name = "TIERS_PROPRIETAIRE", length = 10)
	public String getTiersProprietaire() {
		return this.tiersProprietaire;
	}

	public void setTiersProprietaire(String tiersProprietaire) {
		this.tiersProprietaire = tiersProprietaire;
	}

	@Column(name = "ID_DOSADM", precision = 10, scale = 0)
	public Long getIdDosadm() {
		return this.idDosadm;
	}

	public void setIdDosadm(Long idDosadm) {
		this.idDosadm = idDosadm;
	}

	@Column(name = "CODE_PROTECTION", length = 4)
	public String getCodeProtection() {
		return this.codeProtection;
	}

	public void setCodeProtection(String codeProtection) {
		this.codeProtection = codeProtection;
	}

	@Column(name = "NO_CLASSEMENT", length = 10)
	public String getNoClassement() {
		return this.noClassement;
	}

	public void setNoClassement(String noClassement) {
		this.noClassement = noClassement;
	}

	@Column(name = "CODE_STATUT_IMPOSE", length = 4)
	public String getCodeStatutImpose() {
		return this.codeStatutImpose;
	}

	public void setCodeStatutImpose(String codeStatutImpose) {
		this.codeStatutImpose = codeStatutImpose;
	}

	@Column(name = "CODE_STATUT_COMPTA", length = 4)
	public String getCodeStatutCompta() {
		return this.codeStatutCompta;
	}

	public void setCodeStatutCompta(String codeStatutCompta) {
		this.codeStatutCompta = codeStatutCompta;
	}

	@Column(name = "DATE_PRISE_EN_CHARGE", precision = 10, scale = 0)
	public Long getDatePriseEnCharge() {
		return this.datePriseEnCharge;
	}

	public void setDatePriseEnCharge(Long datePriseEnCharge) {
		this.datePriseEnCharge = datePriseEnCharge;
	}

	@Column(name = "CODE_MODELE_RELEVE", length = 4)
	public String getCodeModeleReleve() {
		return this.codeModeleReleve;
	}

	public void setCodeModeleReleve(String codeModeleReleve) {
		this.codeModeleReleve = codeModeleReleve;
	}

	@Column(name = "ID_CHANGE_DEVR_DEVA", precision = 10, scale = 0)
	public Long getIdChangeDevrDeva() {
		return this.idChangeDevrDeva;
	}

	public void setIdChangeDevrDeva(Long idChangeDevrDeva) {
		this.idChangeDevrDeva = idChangeDevrDeva;
	}

	@Column(name = "CODE_OFFRE", length = 4)
	public String getCodeOffre() {
		return this.codeOffre;
	}

	public void setCodeOffre(String codeOffre) {
		this.codeOffre = codeOffre;
	}

	@Column(name = "TAUX_RECUPERATION", precision = 11, scale = 6)
	public BigDecimal getTauxRecuperation() {
		return this.tauxRecuperation;
	}

	public void setTauxRecuperation(BigDecimal tauxRecuperation) {
		this.tauxRecuperation = tauxRecuperation;
	}

	@Column(name = "NB_JOURS_SCRIVENER", precision = 2, scale = 0)
	public Byte getNbJoursScrivener() {
		return this.nbJoursScrivener;
	}

	public void setNbJoursScrivener(Byte nbJoursScrivener) {
		this.nbJoursScrivener = nbJoursScrivener;
	}

	@Column(name = "DATE_EXP_SCRIVENER", precision = 10, scale = 0)
	public Long getDateExpScrivener() {
		return this.dateExpScrivener;
	}

	public void setDateExpScrivener(Long dateExpScrivener) {
		this.dateExpScrivener = dateExpScrivener;
	}

	@Column(name = "CODE_REGION_INT", length = 4)
	public String getCodeRegionInt() {
		return this.codeRegionInt;
	}

	public void setCodeRegionInt(String codeRegionInt) {
		this.codeRegionInt = codeRegionInt;
	}

	@Column(name = "CODE_SECTEUR", length = 4)
	public String getCodeSecteur() {
		return this.codeSecteur;
	}

	public void setCodeSecteur(String codeSecteur) {
		this.codeSecteur = codeSecteur;
	}

	@Column(name = "CODE_NEIERTZ", length = 4)
	public String getCodeNeiertz() {
		return this.codeNeiertz;
	}

	public void setCodeNeiertz(String codeNeiertz) {
		this.codeNeiertz = codeNeiertz;
	}

	@Column(name = "CODE_TRT_FACTURATION", length = 4)
	public String getCodeTrtFacturation() {
		return this.codeTrtFacturation;
	}

	public void setCodeTrtFacturation(String codeTrtFacturation) {
		this.codeTrtFacturation = codeTrtFacturation;
	}

	@Column(name = "NB_MAX_INCIDENTS", precision = 3, scale = 0)
	public Short getNbMaxIncidents() {
		return this.nbMaxIncidents;
	}

	public void setNbMaxIncidents(Short nbMaxIncidents) {
		this.nbMaxIncidents = nbMaxIncidents;
	}

	@Column(name = "CODE_STATUT_RISQUE", length = 4)
	public String getCodeStatutRisque() {
		return this.codeStatutRisque;
	}

	public void setCodeStatutRisque(String codeStatutRisque) {
		this.codeStatutRisque = codeStatutRisque;
	}

	@Column(name = "FLAG_CONVERSION", length = 4)
	public String getFlagConversion() {
		return this.flagConversion;
	}

	public void setFlagConversion(String flagConversion) {
		this.flagConversion = flagConversion;
	}

	@Column(name = "CODE_DEVISE_AVT_EURO", length = 4)
	public String getCodeDeviseAvtEuro() {
		return this.codeDeviseAvtEuro;
	}

	public void setCodeDeviseAvtEuro(String codeDeviseAvtEuro) {
		this.codeDeviseAvtEuro = codeDeviseAvtEuro;
	}

	@Column(name = "INDICATEUR_CONVERSION", length = 1)
	public String getIndicateurConversion() {
		return this.indicateurConversion;
	}

	public void setIndicateurConversion(String indicateurConversion) {
		this.indicateurConversion = indicateurConversion;
	}

	@Column(name = "NUM_AVT_EURO", precision = 11, scale = 6)
	public BigDecimal getNumAvtEuro() {
		return this.numAvtEuro;
	}

	public void setNumAvtEuro(BigDecimal numAvtEuro) {
		this.numAvtEuro = numAvtEuro;
	}

	@Column(name = "DENO_AVT_EURO", precision = 11, scale = 6)
	public BigDecimal getDenoAvtEuro() {
		return this.denoAvtEuro;
	}

	public void setDenoAvtEuro(BigDecimal denoAvtEuro) {
		this.denoAvtEuro = denoAvtEuro;
	}

	@Column(name = "FLAG_TRANCHE", length = 1)
	public String getFlagTranche() {
		return this.flagTranche;
	}

	public void setFlagTranche(String flagTranche) {
		this.flagTranche = flagTranche;
	}

	@Column(name = "ID_CONCADRE", precision = 10, scale = 0)
	public Long getIdConcadre() {
		return this.idConcadre;
	}

	public void setIdConcadre(Long idConcadre) {
		this.idConcadre = idConcadre;
	}

	@Column(name = "CODE_BALLON", length = 4)
	public String getCodeBallon() {
		return this.codeBallon;
	}

	public void setCodeBallon(String codeBallon) {
		this.codeBallon = codeBallon;
	}

	@Column(name = "POURCENTAGE_ROR", precision = 11, scale = 6)
	public BigDecimal getPourcentageRor() {
		return this.pourcentageRor;
	}

	public void setPourcentageRor(BigDecimal pourcentageRor) {
		this.pourcentageRor = pourcentageRor;
	}

	@Column(name = "CODE_TAUX_SUSPENSION", length = 4)
	public String getCodeTauxSuspension() {
		return this.codeTauxSuspension;
	}

	public void setCodeTauxSuspension(String codeTauxSuspension) {
		this.codeTauxSuspension = codeTauxSuspension;
	}

	@Column(name = "CODE_TITRISATION", length = 4)
	public String getCodeTitrisation() {
		return this.codeTitrisation;
	}

	public void setCodeTitrisation(String codeTitrisation) {
		this.codeTitrisation = codeTitrisation;
	}

	@Column(name = "ID_AFFAIRE_GLB", precision = 10, scale = 0)
	public Long getIdAffaireGlb() {
		return this.idAffaireGlb;
	}

	public void setIdAffaireGlb(Long idAffaireGlb) {
		this.idAffaireGlb = idAffaireGlb;
	}

	@Column(name = "FLAG_AFFAIRE_GLB", length = 1)
	public String getFlagAffaireGlb() {
		return this.flagAffaireGlb;
	}

	public void setFlagAffaireGlb(String flagAffaireGlb) {
		this.flagAffaireGlb = flagAffaireGlb;
	}

	@Column(name = "FLAG_GLB_FACTURE", length = 1)
	public String getFlagGlbFacture() {
		return this.flagGlbFacture;
	}

	public void setFlagGlbFacture(String flagGlbFacture) {
		this.flagGlbFacture = flagGlbFacture;
	}

	@Column(name = "CODE_TYPE_DUREE", length = 4)
	public String getCodeTypeDuree() {
		return this.codeTypeDuree;
	}

	public void setCodeTypeDuree(String codeTypeDuree) {
		this.codeTypeDuree = codeTypeDuree;
	}

	@Column(name = "CODE_CALC_ARRETE", length = 4)
	public String getCodeCalcArrete() {
		return this.codeCalcArrete;
	}

	public void setCodeCalcArrete(String codeCalcArrete) {
		this.codeCalcArrete = codeCalcArrete;
	}

	@Column(name = "MA_ID_AFFAIRE_SUB", precision = 10, scale = 0)
	public Long getMaIdAffaireSub() {
		return this.maIdAffaireSub;
	}

	public void setMaIdAffaireSub(Long maIdAffaireSub) {
		this.maIdAffaireSub = maIdAffaireSub;
	}

	@Column(name = "CODE_TTAS", length = 4)
	public String getCodeTtas() {
		return this.codeTtas;
	}

	public void setCodeTtas(String codeTtas) {
		this.codeTtas = codeTtas;
	}

	@Column(name = "ASNEF_NUMBER", precision = 8, scale = 0)
	public Integer getAsnefNumber() {
		return this.asnefNumber;
	}

	public void setAsnefNumber(Integer asnefNumber) {
		this.asnefNumber = asnefNumber;
	}

	@Column(name = "CODE_RESTRUCTURATION", length = 4)
	public String getCodeRestructuration() {
		return this.codeRestructuration;
	}

	public void setCodeRestructuration(String codeRestructuration) {
		this.codeRestructuration = codeRestructuration;
	}

	@Column(name = "NO_PARTITION", precision = 10, scale = 0)
	public Long getNoPartition() {
		return this.noPartition;
	}

	public void setNoPartition(Long noPartition) {
		this.noPartition = noPartition;
	}

	@Column(name = "ID_AFFAIRE_RENOUVELEE", precision = 10, scale = 0)
	public Long getIdAffaireRenouvelee() {
		return this.idAffaireRenouvelee;
	}

	public void setIdAffaireRenouvelee(Long idAffaireRenouvelee) {
		this.idAffaireRenouvelee = idAffaireRenouvelee;
	}

	@Column(name = "REF_COMMERCIALE", length = 30)
	public String getRefCommerciale() {
		return this.refCommerciale;
	}

	public void setRefCommerciale(String refCommerciale) {
		this.refCommerciale = refCommerciale;
	}

	@Column(name = "ID_GROUPE_SGT", precision = 10, scale = 0)
	public Long getIdGroupeSgt() {
		return this.idGroupeSgt;
	}

	public void setIdGroupeSgt(Long idGroupeSgt) {
		this.idGroupeSgt = idGroupeSgt;
	}

	@Column(name = "ID_GRPAFFARC", precision = 11, scale = 0)
	public Long getIdGrpaffarc() {
		return this.idGrpaffarc;
	}

	public void setIdGrpaffarc(Long idGrpaffarc) {
		this.idGrpaffarc = idGrpaffarc;
	}

	@Column(name = "CODE_FORCAGE_IE_AFF", length = 4)
	public String getCodeForcageIeAff() {
		return this.codeForcageIeAff;
	}

	public void setCodeForcageIeAff(String codeForcageIeAff) {
		this.codeForcageIeAff = codeForcageIeAff;
	}

}
