package com.sofac.models;
// Generated 2 mai 2017 11:47:09 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.hibernate.annotations.Type;

/**
 * AfftiersId generated by hbm2java
 */
@Embeddable
public class AfftiersId implements java.io.Serializable {

	private String tiers1;

	private String codeNatTiers;

	private long dateEffet;

	private long noOrdre;
	private long idAffaire;

	public AfftiersId() {
	}

	public AfftiersId(String tiers1, String codeNatTiers, long dateEffet, long noOrdre, long idAffaire) {
		this.tiers1 = tiers1;
		this.codeNatTiers = codeNatTiers;
		this.dateEffet = dateEffet;
		this.noOrdre = noOrdre;
		this.idAffaire = idAffaire;
	}

	@Column(name = "TIERS_1", nullable = false, length = 10)
	public String getTiers1() {
		return this.tiers1;
	}

	public void setTiers1(String tiers1) {
		this.tiers1 = tiers1;
	}

	@Column(name = "CODE_NAT_TIERS", nullable = false, length = 4)
	public String getCodeNatTiers() {
		return this.codeNatTiers;
	}

	public void setCodeNatTiers(String codeNatTiers) {
		this.codeNatTiers = codeNatTiers;
	}

	@Column(name = "DATE_EFFET", nullable = false, precision = 10, scale = 0)
	public long getDateEffet() {
		return this.dateEffet;
	}

	public void setDateEffet(long dateEffet) {
		this.dateEffet = dateEffet;
	}

	@Column(name = "NO_ORDRE", nullable = false, precision = 10, scale = 0)
	public long getNoOrdre() {
		return this.noOrdre;
	}

	public void setNoOrdre(long noOrdre) {
		this.noOrdre = noOrdre;
	}

	@Column(name = "ID_AFFAIRE", nullable = false, precision = 10, scale = 0)
	public long getIdAffaire() {
		return this.idAffaire;
	}

	public void setIdAffaire(long idAffaire) {
		this.idAffaire = idAffaire;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codeNatTiers == null) ? 0 : codeNatTiers.hashCode());
		result = prime * result + (int) (dateEffet ^ (dateEffet >>> 32));
		result = prime * result + (int) (idAffaire ^ (idAffaire >>> 32));
		result = prime * result + (int) (noOrdre ^ (noOrdre >>> 32));
		result = prime * result + ((tiers1 == null) ? 0 : tiers1.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AfftiersId other = (AfftiersId) obj;
		if (codeNatTiers == null) {
			if (other.codeNatTiers != null)
				return false;
		} else if (!codeNatTiers.equals(other.codeNatTiers))
			return false;
		if (dateEffet != other.dateEffet)
			return false;
		if (idAffaire != other.idAffaire)
			return false;
		if (noOrdre != other.noOrdre)
			return false;
		if (tiers1 == null) {
			if (other.tiers1 != null)
				return false;
		} else if (!tiers1.equals(other.tiers1))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "AfftiersId [tiers1=" + tiers1 + ", codeNatTiers=" + codeNatTiers + ", dateEffet=" + dateEffet
				+ ", noOrdre=" + noOrdre + ", idAffaire=" + idAffaire + "]";
	}
}
