package com.sofac.models;
// Generated 2 mai 2017 11:47:09 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpltiersId generated by hbm2java
 */
@Embeddable
public class EmpltiersId implements java.io.Serializable {

	private String tiers;
	private String raisonSociale;
	

	public EmpltiersId() {
	}

	public EmpltiersId(String tiers, String raisonSociale) {
		this.tiers = tiers;
		this.raisonSociale = raisonSociale;
	}

	@Column(name = "TIERS", nullable = false, length = 10)
	public String getTiers() {
		return this.tiers;
	}

	public void setTiers(String tiers) {
		this.tiers = tiers;
	}

	@Column(name = "RAISON_SOCIALE", length = 80)
	public String getRaisonSociale() {
		return this.raisonSociale;
	}

	public void setRaisonSociale(String raisonSociale) {
		this.raisonSociale = raisonSociale;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((raisonSociale == null) ? 0 : raisonSociale.hashCode());
		result = prime * result + ((tiers == null) ? 0 : tiers.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EmpltiersId other = (EmpltiersId) obj;
		if (raisonSociale == null) {
			if (other.raisonSociale != null)
				return false;
		} else if (!raisonSociale.equals(other.raisonSociale))
			return false;
		if (tiers == null) {
			if (other.tiers != null)
				return false;
		} else if (!tiers.equals(other.tiers))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "EmpltiersId [tiers=" + tiers + ", raisonSociale=" + raisonSociale + "]";
	}
}
