package com.sofac.models;
// Generated 2 mai 2017 11:47:09 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Empltiers generated by hbm2java
 */
@Entity
@Table(name = "EMPLTIERS", schema = "OPS$INGENETUDES")
public class Empltiers implements java.io.Serializable {

	private EmpltiersId id;
	private String adresse1;
	private String adresse2;
	private String codePostal;
	private String ville;
	private String telephone;
	private BigDecimal mtCapital0ma;
	private BigDecimal nbEmploye0ma;

	public Empltiers() {
	}

	public Empltiers(EmpltiersId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tiers", column = @Column(name = "TIERS", nullable = false, length = 10)),
			@AttributeOverride(name = "raisonSociale", column = @Column(name = "RAISON_SOCIALE", length = 80))})
	public EmpltiersId getId() {
		return this.id;
	}

	public void setId(EmpltiersId id) {
		this.id = id;
	}

	@Column(name = "ADRESSE_1", length = 80)
	public String getAdresse1() {
		return this.adresse1;
	}

	public void setAdresse1(String adresse1) {
		this.adresse1 = adresse1;
	}

	@Column(name = "ADRESSE_2", length = 80)
	public String getAdresse2() {
		return this.adresse2;
	}

	public void setAdresse2(String adresse2) {
		this.adresse2 = adresse2;
	}

	@Column(name = "CODE_POSTAL", length = 10)
	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "VILLE", length = 60)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "TELEPHONE", length = 30)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "MT_CAPITAL_0MA", precision = 18, scale = 3)
	public BigDecimal getMtCapital0ma() {
		return this.mtCapital0ma;
	}

	public void setMtCapital0ma(BigDecimal mtCapital0ma) {
		this.mtCapital0ma = mtCapital0ma;
	}

	@Column(name = "NB_EMPLOYE_0MA", precision = 22, scale = 0)
	public BigDecimal getNbEmploye0ma() {
		return this.nbEmploye0ma;
	}

	public void setNbEmploye0ma(BigDecimal nbEmploye0ma) {
		this.nbEmploye0ma = nbEmploye0ma;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((adresse1 == null) ? 0 : adresse1.hashCode());
		result = prime * result + ((adresse2 == null) ? 0 : adresse2.hashCode());
		result = prime * result + ((codePostal == null) ? 0 : codePostal.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((mtCapital0ma == null) ? 0 : mtCapital0ma.hashCode());
		result = prime * result + ((nbEmploye0ma == null) ? 0 : nbEmploye0ma.hashCode());
		result = prime * result + ((telephone == null) ? 0 : telephone.hashCode());
		result = prime * result + ((ville == null) ? 0 : ville.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Empltiers other = (Empltiers) obj;
		if (adresse1 == null) {
			if (other.adresse1 != null)
				return false;
		} else if (!adresse1.equals(other.adresse1))
			return false;
		if (adresse2 == null) {
			if (other.adresse2 != null)
				return false;
		} else if (!adresse2.equals(other.adresse2))
			return false;
		if (codePostal == null) {
			if (other.codePostal != null)
				return false;
		} else if (!codePostal.equals(other.codePostal))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (mtCapital0ma == null) {
			if (other.mtCapital0ma != null)
				return false;
		} else if (!mtCapital0ma.equals(other.mtCapital0ma))
			return false;
		if (nbEmploye0ma == null) {
			if (other.nbEmploye0ma != null)
				return false;
		} else if (!nbEmploye0ma.equals(other.nbEmploye0ma))
			return false;
		if (telephone == null) {
			if (other.telephone != null)
				return false;
		} else if (!telephone.equals(other.telephone))
			return false;
		if (ville == null) {
			if (other.ville != null)
				return false;
		} else if (!ville.equals(other.ville))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Empltiers [id=" + id + ", adresse1=" + adresse1 + ", adresse2=" + adresse2 + ", codePostal="
				+ codePostal + ", ville=" + ville + ", telephone=" + telephone + ", mtCapital0ma=" + mtCapital0ma
				+ ", nbEmploye0ma=" + nbEmploye0ma + "]";
	}
}
