package com.sofac.models;
// Generated 2 mai 2017 11:47:09 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RefcommId generated by hbm2java
 */
@Embeddable
public class RefcommId implements java.io.Serializable {

	private long idRefcomm;
	private String tiers;
	private String codeReference;
	

	public RefcommId() {
	}

	public RefcommId(long idRefcomm, String tiers, String codeReference) {
		this.idRefcomm = idRefcomm;
		this.tiers = tiers;
		this.codeReference = codeReference;
	}

	@Column(name = "ID_REFCOMM", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdRefcomm() {
		return this.idRefcomm;
	}

	public void setIdRefcomm(long idRefcomm) {
		this.idRefcomm = idRefcomm;
	}

	@Column(name = "TIERS", nullable = false, length = 10)
	public String getTiers() {
		return this.tiers;
	}

	public void setTiers(String tiers) {
		this.tiers = tiers;
	}

	@Column(name = "CODE_REFERENCE", nullable = false, length = 4)
	public String getCodeReference() {
		return this.codeReference;
	}

	public void setCodeReference(String codeReference) {
		this.codeReference = codeReference;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codeReference == null) ? 0 : codeReference.hashCode());
		result = prime * result + (int) (idRefcomm ^ (idRefcomm >>> 32));
		result = prime * result + ((tiers == null) ? 0 : tiers.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		RefcommId other = (RefcommId) obj;
		if (codeReference == null) {
			if (other.codeReference != null)
				return false;
		} else if (!codeReference.equals(other.codeReference))
			return false;
		if (idRefcomm != other.idRefcomm)
			return false;
		if (tiers == null) {
			if (other.tiers != null)
				return false;
		} else if (!tiers.equals(other.tiers))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "RefcommId [idRefcomm=" + idRefcomm + ", tiers=" + tiers + ", codeReference=" + codeReference + "]";
	}
}
