package com.sofac.models;
// Generated 2 mai 2017 11:47:09 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tieiden generated by hbm2java
 */
@Entity
@Table(name = "TIEIDEN", schema = "OPS$INGENETUDES")
public class Tieiden implements java.io.Serializable {

	private long idTieiden;
	private String tiers;
	private String codePieceIden;
	private String noPieceIden;
	private long dateDebutValidite;
	private Long dateFinValidite;
	private String lieuDelivrance;
	private String codeArchivageLieu;

	public Tieiden() {
	}

	public Tieiden(long idTieiden, String tiers, String codePieceIden, String noPieceIden, long dateDebutValidite) {
		this.idTieiden = idTieiden;
		this.tiers = tiers;
		this.codePieceIden = codePieceIden;
		this.noPieceIden = noPieceIden;
		this.dateDebutValidite = dateDebutValidite;
	}

	public Tieiden(long idTieiden, String tiers, String codePieceIden, String noPieceIden, long dateDebutValidite,
			Long dateFinValidite, String lieuDelivrance, String codeArchivageLieu) {
		this.idTieiden = idTieiden;
		this.tiers = tiers;
		this.codePieceIden = codePieceIden;
		this.noPieceIden = noPieceIden;
		this.dateDebutValidite = dateDebutValidite;
		this.dateFinValidite = dateFinValidite;
		this.lieuDelivrance = lieuDelivrance;
		this.codeArchivageLieu = codeArchivageLieu;
	}

	@Id

	@Column(name = "ID_TIEIDEN", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdTieiden() {
		return this.idTieiden;
	}

	public void setIdTieiden(long idTieiden) {
		this.idTieiden = idTieiden;
	}

	@Column(name = "TIERS", nullable = false, length = 10)
	public String getTiers() {
		return this.tiers;
	}

	public void setTiers(String tiers) {
		this.tiers = tiers;
	}

	@Column(name = "CODE_PIECE_IDEN", nullable = false, length = 4)
	public String getCodePieceIden() {
		return this.codePieceIden;
	}

	public void setCodePieceIden(String codePieceIden) {
		this.codePieceIden = codePieceIden;
	}

	@Column(name = "NO_PIECE_IDEN", nullable = false, length = 30)
	public String getNoPieceIden() {
		return this.noPieceIden;
	}

	public void setNoPieceIden(String noPieceIden) {
		this.noPieceIden = noPieceIden;
	}

	@Column(name = "DATE_DEBUT_VALIDITE", nullable = false, precision = 10, scale = 0)
	public long getDateDebutValidite() {
		return this.dateDebutValidite;
	}

	public void setDateDebutValidite(long dateDebutValidite) {
		this.dateDebutValidite = dateDebutValidite;
	}

	@Column(name = "DATE_FIN_VALIDITE", precision = 10, scale = 0)
	public Long getDateFinValidite() {
		return this.dateFinValidite;
	}

	public void setDateFinValidite(Long dateFinValidite) {
		this.dateFinValidite = dateFinValidite;
	}

	@Column(name = "LIEU_DELIVRANCE", length = 60)
	public String getLieuDelivrance() {
		return this.lieuDelivrance;
	}

	public void setLieuDelivrance(String lieuDelivrance) {
		this.lieuDelivrance = lieuDelivrance;
	}

	@Column(name = "CODE_ARCHIVAGE_LIEU", length = 4)
	public String getCodeArchivageLieu() {
		return this.codeArchivageLieu;
	}

	public void setCodeArchivageLieu(String codeArchivageLieu) {
		this.codeArchivageLieu = codeArchivageLieu;
	}

}
