package com.sofac.models;
// Generated 2 mai 2017 11:47:09 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tiers generated by hbm2java
 */
@Entity
@Table(name = "TIERS", schema = "OPS$INGENETUDES")
public class Tiers implements java.io.Serializable {

	private long idTiers;
	private String tiers;
	private String codeTypePersonne;
	private String codePays;
	private String codeQualite;
	private String initiale;
	private String nomCourt;
	private String nom;
	private String preposition;
	private String codeLangue;
	private String codeTypeTiers;
	private String prenom;
	private String nomJeuneFille;
	private String codeNationalite;
	private Long dateNaissance;
	private String codePostal1;
	private String codePostal2;
	private String lieuNaissance;
	private String codeInsee;
	private String flagResident;
	private String codeRegMatri;
	private Byte nbEnfant;
	private String codePropParticulier;
	private String flagAutreProp;
	private BigDecimal mtCharge;
	private String codeProfession;
	private String flagSalarie;
	private BigDecimal mtSalaire;
	private BigDecimal mtAutreRevenu;
	private Short nbMoisAnciennete;
	private String codeContratTravail;
	private String siret1;
	private String siret2;
	private String siret3;
	private String siret4;
	private String raisonSociale1;
	private String raisonSociale2;
	private String raisonSociale3;
	private Long dateDebAct;
	private Long dateFinAct;
	private String codeActivite;
	private String codeCategorieTiers;
	private String categorieInsee;
	private BigDecimal mtCapital;
	private Integer nbEmploye;
	private String representant;
	private String prenomRepresentant;
	private String enQualite;
	private String noRc;
	private String codeApe;
	private String flagProprietaire;
	private String flagPropFond;
	private String flagTaxePro;
	private String nif;
	private String codeTerritorialite;
	private String codeRegrDec;
	private String codeRegrEnc;
	private String tiersConsolidation;
	private String codeRegimeFiscal;
	private String nomaffTiers;
	private Byte moisBilan;
	private Byte jourBilan;
	private String banque;
	private String banqueDeFrance;
	private String guichet;
	private String codeDevise;
	private String codeGroupe;
	private String villeRc;
	private String tvaIntracomm;
	private String codeReseau;
	private String codeRegion;
	private String telephoneChc;
	private Long dateContact;
	private Integer codeBanqueIngnl;
	private String tiersAgence;
	private String tiersAccm;
	private String codeBik;
	private String referenceExterne;
	private String codeNbremp;
	private String codeStatutImpose;
	private String cotationOfficielle;
	private String identifiantBdf;
	private String flagIdentPrincipal;
	private String codeTypeRevenu;
	private BigDecimal montantRevenu;
	private Long datePresence;
	private String flagReversTva;
	private String codeNaceTiers;
	private String prefixTiers;
	private String titleTiers;
	private String nipNumber;
	private BigDecimal regonNumber;
	private BigDecimal autresCharges;
	private String codeClassifMarche;
	private String codeClassifSegment;
	private String flagRecupTva;
	private Long dateEntreeEmploi;
	private Long dateEntreeLgt;
	private String flagConversion;
	private String indicateurConversion;
	private BigDecimal numAvtEuro;
	private BigDecimal denoAvtEuro;
	private String nomedtTiers1;
	private String nomedtTiers2;
	private String nomedtTiers3;
	private BigDecimal mtRevenusConjoint;
	private String codeInseeNaiss;
	private Long dateJugement;
	private String nomedtTiers4;
	private String nomedtTiers5;
	private String nomedtTiers6;
	private String nomedtTiers7;
	private String nomedtTiers8;
	private String nomedtTiers9;
	private String nomedtTiers10;
	private String nomMajuscule;
	private String codActBam;
	private String erreurDebBam;
	private String erreurMajbBam;
	private String numRisqueBam;
	private String noGrefExperian;
	private String rechTiers1;
	private String rechTiers2;
	private String codeVip;
	private String codeSae;
	private String codeRae;
	private String codeSexe;
	private Long idGroupeSgt;
	private String codeModeCreation;
	private String codeConsolidation;
	private String codeStatut;
	private long idMasquage;
	private String numeroNationalId;

	public Tiers() {
	}

	public Tiers(long idTiers, String tiers, long idMasquage) {
		this.idTiers = idTiers;
		this.tiers = tiers;
		this.idMasquage = idMasquage;
	}

	public Tiers(long idTiers, String tiers, String codeTypePersonne, String codePays, String codeQualite,
			String initiale, String nomCourt, String nom, String preposition, String codeLangue, String codeTypeTiers,
			String prenom, String nomJeuneFille, String codeNationalite, Long dateNaissance, String codePostal1,
			String codePostal2, String lieuNaissance, String codeInsee, String flagResident, String codeRegMatri,
			Byte nbEnfant, String codePropParticulier, String flagAutreProp, BigDecimal mtCharge, String codeProfession,
			String flagSalarie, BigDecimal mtSalaire, BigDecimal mtAutreRevenu, Short nbMoisAnciennete,
			String codeContratTravail, String siret1, String siret2, String siret3, String siret4,
			String raisonSociale1, String raisonSociale2, String raisonSociale3, Long dateDebAct, Long dateFinAct,
			String codeActivite, String codeCategorieTiers, String categorieInsee, BigDecimal mtCapital,
			Integer nbEmploye, String representant, String prenomRepresentant, String enQualite, String noRc,
			String codeApe, String flagProprietaire, String flagPropFond, String flagTaxePro, String nif,
			String codeTerritorialite, String codeRegrDec, String codeRegrEnc, String tiersConsolidation,
			String codeRegimeFiscal, String nomaffTiers, Byte moisBilan, Byte jourBilan, String banque,
			String banqueDeFrance, String guichet, String codeDevise, String codeGroupe, String villeRc,
			String tvaIntracomm, String codeReseau, String codeRegion, String telephoneChc, Long dateContact,
			Integer codeBanqueIngnl, String tiersAgence, String tiersAccm, String codeBik, String referenceExterne,
			String codeNbremp, String codeStatutImpose, String cotationOfficielle, String identifiantBdf,
			String flagIdentPrincipal, String codeTypeRevenu, BigDecimal montantRevenu, Long datePresence,
			String flagReversTva, String codeNaceTiers, String prefixTiers, String titleTiers, String nipNumber,
			BigDecimal regonNumber, BigDecimal autresCharges, String codeClassifMarche, String codeClassifSegment,
			String flagRecupTva, Long dateEntreeEmploi, Long dateEntreeLgt, String flagConversion,
			String indicateurConversion, BigDecimal numAvtEuro, BigDecimal denoAvtEuro, String nomedtTiers1,
			String nomedtTiers2, String nomedtTiers3, BigDecimal mtRevenusConjoint, String codeInseeNaiss,
			Long dateJugement, String nomedtTiers4, String nomedtTiers5, String nomedtTiers6, String nomedtTiers7,
			String nomedtTiers8, String nomedtTiers9, String nomedtTiers10, String nomMajuscule, String codActBam,
			String erreurDebBam, String erreurMajbBam, String numRisqueBam, String noGrefExperian, String rechTiers1,
			String rechTiers2, String codeVip, String codeSae, String codeRae, String codeSexe, Long idGroupeSgt,
			String codeModeCreation, String codeConsolidation, String codeStatut, long idMasquage,
			String numeroNationalId) {
		this.idTiers = idTiers;
		this.tiers = tiers;
		this.codeTypePersonne = codeTypePersonne;
		this.codePays = codePays;
		this.codeQualite = codeQualite;
		this.initiale = initiale;
		this.nomCourt = nomCourt;
		this.nom = nom;
		this.preposition = preposition;
		this.codeLangue = codeLangue;
		this.codeTypeTiers = codeTypeTiers;
		this.prenom = prenom;
		this.nomJeuneFille = nomJeuneFille;
		this.codeNationalite = codeNationalite;
		this.dateNaissance = dateNaissance;
		this.codePostal1 = codePostal1;
		this.codePostal2 = codePostal2;
		this.lieuNaissance = lieuNaissance;
		this.codeInsee = codeInsee;
		this.flagResident = flagResident;
		this.codeRegMatri = codeRegMatri;
		this.nbEnfant = nbEnfant;
		this.codePropParticulier = codePropParticulier;
		this.flagAutreProp = flagAutreProp;
		this.mtCharge = mtCharge;
		this.codeProfession = codeProfession;
		this.flagSalarie = flagSalarie;
		this.mtSalaire = mtSalaire;
		this.mtAutreRevenu = mtAutreRevenu;
		this.nbMoisAnciennete = nbMoisAnciennete;
		this.codeContratTravail = codeContratTravail;
		this.siret1 = siret1;
		this.siret2 = siret2;
		this.siret3 = siret3;
		this.siret4 = siret4;
		this.raisonSociale1 = raisonSociale1;
		this.raisonSociale2 = raisonSociale2;
		this.raisonSociale3 = raisonSociale3;
		this.dateDebAct = dateDebAct;
		this.dateFinAct = dateFinAct;
		this.codeActivite = codeActivite;
		this.codeCategorieTiers = codeCategorieTiers;
		this.categorieInsee = categorieInsee;
		this.mtCapital = mtCapital;
		this.nbEmploye = nbEmploye;
		this.representant = representant;
		this.prenomRepresentant = prenomRepresentant;
		this.enQualite = enQualite;
		this.noRc = noRc;
		this.codeApe = codeApe;
		this.flagProprietaire = flagProprietaire;
		this.flagPropFond = flagPropFond;
		this.flagTaxePro = flagTaxePro;
		this.nif = nif;
		this.codeTerritorialite = codeTerritorialite;
		this.codeRegrDec = codeRegrDec;
		this.codeRegrEnc = codeRegrEnc;
		this.tiersConsolidation = tiersConsolidation;
		this.codeRegimeFiscal = codeRegimeFiscal;
		this.nomaffTiers = nomaffTiers;
		this.moisBilan = moisBilan;
		this.jourBilan = jourBilan;
		this.banque = banque;
		this.banqueDeFrance = banqueDeFrance;
		this.guichet = guichet;
		this.codeDevise = codeDevise;
		this.codeGroupe = codeGroupe;
		this.villeRc = villeRc;
		this.tvaIntracomm = tvaIntracomm;
		this.codeReseau = codeReseau;
		this.codeRegion = codeRegion;
		this.telephoneChc = telephoneChc;
		this.dateContact = dateContact;
		this.codeBanqueIngnl = codeBanqueIngnl;
		this.tiersAgence = tiersAgence;
		this.tiersAccm = tiersAccm;
		this.codeBik = codeBik;
		this.referenceExterne = referenceExterne;
		this.codeNbremp = codeNbremp;
		this.codeStatutImpose = codeStatutImpose;
		this.cotationOfficielle = cotationOfficielle;
		this.identifiantBdf = identifiantBdf;
		this.flagIdentPrincipal = flagIdentPrincipal;
		this.codeTypeRevenu = codeTypeRevenu;
		this.montantRevenu = montantRevenu;
		this.datePresence = datePresence;
		this.flagReversTva = flagReversTva;
		this.codeNaceTiers = codeNaceTiers;
		this.prefixTiers = prefixTiers;
		this.titleTiers = titleTiers;
		this.nipNumber = nipNumber;
		this.regonNumber = regonNumber;
		this.autresCharges = autresCharges;
		this.codeClassifMarche = codeClassifMarche;
		this.codeClassifSegment = codeClassifSegment;
		this.flagRecupTva = flagRecupTva;
		this.dateEntreeEmploi = dateEntreeEmploi;
		this.dateEntreeLgt = dateEntreeLgt;
		this.flagConversion = flagConversion;
		this.indicateurConversion = indicateurConversion;
		this.numAvtEuro = numAvtEuro;
		this.denoAvtEuro = denoAvtEuro;
		this.nomedtTiers1 = nomedtTiers1;
		this.nomedtTiers2 = nomedtTiers2;
		this.nomedtTiers3 = nomedtTiers3;
		this.mtRevenusConjoint = mtRevenusConjoint;
		this.codeInseeNaiss = codeInseeNaiss;
		this.dateJugement = dateJugement;
		this.nomedtTiers4 = nomedtTiers4;
		this.nomedtTiers5 = nomedtTiers5;
		this.nomedtTiers6 = nomedtTiers6;
		this.nomedtTiers7 = nomedtTiers7;
		this.nomedtTiers8 = nomedtTiers8;
		this.nomedtTiers9 = nomedtTiers9;
		this.nomedtTiers10 = nomedtTiers10;
		this.nomMajuscule = nomMajuscule;
		this.codActBam = codActBam;
		this.erreurDebBam = erreurDebBam;
		this.erreurMajbBam = erreurMajbBam;
		this.numRisqueBam = numRisqueBam;
		this.noGrefExperian = noGrefExperian;
		this.rechTiers1 = rechTiers1;
		this.rechTiers2 = rechTiers2;
		this.codeVip = codeVip;
		this.codeSae = codeSae;
		this.codeRae = codeRae;
		this.codeSexe = codeSexe;
		this.idGroupeSgt = idGroupeSgt;
		this.codeModeCreation = codeModeCreation;
		this.codeConsolidation = codeConsolidation;
		this.codeStatut = codeStatut;
		this.idMasquage = idMasquage;
		this.numeroNationalId = numeroNationalId;
	}

	@Id

	@Column(name = "ID_TIERS", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdTiers() {
		return this.idTiers;
	}

	public void setIdTiers(long idTiers) {
		this.idTiers = idTiers;
	}

	@Column(name = "TIERS", nullable = false, length = 10)
	public String getTiers() {
		return this.tiers;
	}

	public void setTiers(String tiers) {
		this.tiers = tiers;
	}

	@Column(name = "CODE_TYPE_PERSONNE", length = 4)
	public String getCodeTypePersonne() {
		return this.codeTypePersonne;
	}

	public void setCodeTypePersonne(String codeTypePersonne) {
		this.codeTypePersonne = codeTypePersonne;
	}

	@Column(name = "CODE_PAYS", length = 4)
	public String getCodePays() {
		return this.codePays;
	}

	public void setCodePays(String codePays) {
		this.codePays = codePays;
	}

	@Column(name = "CODE_QUALITE", length = 4)
	public String getCodeQualite() {
		return this.codeQualite;
	}

	public void setCodeQualite(String codeQualite) {
		this.codeQualite = codeQualite;
	}

	@Column(name = "INITIALE", length = 10)
	public String getInitiale() {
		return this.initiale;
	}

	public void setInitiale(String initiale) {
		this.initiale = initiale;
	}

	@Column(name = "NOM_COURT", length = 20)
	public String getNomCourt() {
		return this.nomCourt;
	}

	public void setNomCourt(String nomCourt) {
		this.nomCourt = nomCourt;
	}

	@Column(name = "NOM")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PREPOSITION", length = 10)
	public String getPreposition() {
		return this.preposition;
	}

	public void setPreposition(String preposition) {
		this.preposition = preposition;
	}

	@Column(name = "CODE_LANGUE", length = 4)
	public String getCodeLangue() {
		return this.codeLangue;
	}

	public void setCodeLangue(String codeLangue) {
		this.codeLangue = codeLangue;
	}

	@Column(name = "CODE_TYPE_TIERS", length = 4)
	public String getCodeTypeTiers() {
		return this.codeTypeTiers;
	}

	public void setCodeTypeTiers(String codeTypeTiers) {
		this.codeTypeTiers = codeTypeTiers;
	}

	@Column(name = "PRENOM")
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "NOM_JEUNE_FILLE", length = 60)
	public String getNomJeuneFille() {
		return this.nomJeuneFille;
	}

	public void setNomJeuneFille(String nomJeuneFille) {
		this.nomJeuneFille = nomJeuneFille;
	}

	@Column(name = "CODE_NATIONALITE", length = 4)
	public String getCodeNationalite() {
		return this.codeNationalite;
	}

	public void setCodeNationalite(String codeNationalite) {
		this.codeNationalite = codeNationalite;
	}

	@Column(name = "DATE_NAISSANCE", precision = 10, scale = 0)
	public Long getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Long dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "CODE_POSTAL_1", length = 10)
	public String getCodePostal1() {
		return this.codePostal1;
	}

	public void setCodePostal1(String codePostal1) {
		this.codePostal1 = codePostal1;
	}

	@Column(name = "CODE_POSTAL_2", length = 10)
	public String getCodePostal2() {
		return this.codePostal2;
	}

	public void setCodePostal2(String codePostal2) {
		this.codePostal2 = codePostal2;
	}

	@Column(name = "LIEU_NAISSANCE", length = 60)
	public String getLieuNaissance() {
		return this.lieuNaissance;
	}

	public void setLieuNaissance(String lieuNaissance) {
		this.lieuNaissance = lieuNaissance;
	}

	@Column(name = "CODE_INSEE", length = 20)
	public String getCodeInsee() {
		return this.codeInsee;
	}

	public void setCodeInsee(String codeInsee) {
		this.codeInsee = codeInsee;
	}

	@Column(name = "FLAG_RESIDENT", length = 4)
	public String getFlagResident() {
		return this.flagResident;
	}

	public void setFlagResident(String flagResident) {
		this.flagResident = flagResident;
	}

	@Column(name = "CODE_REG_MATRI", length = 4)
	public String getCodeRegMatri() {
		return this.codeRegMatri;
	}

	public void setCodeRegMatri(String codeRegMatri) {
		this.codeRegMatri = codeRegMatri;
	}

	@Column(name = "NB_ENFANT", precision = 2, scale = 0)
	public Byte getNbEnfant() {
		return this.nbEnfant;
	}

	public void setNbEnfant(Byte nbEnfant) {
		this.nbEnfant = nbEnfant;
	}

	@Column(name = "CODE_PROP_PARTICULIER", length = 4)
	public String getCodePropParticulier() {
		return this.codePropParticulier;
	}

	public void setCodePropParticulier(String codePropParticulier) {
		this.codePropParticulier = codePropParticulier;
	}

	@Column(name = "FLAG_AUTRE_PROP", length = 4)
	public String getFlagAutreProp() {
		return this.flagAutreProp;
	}

	public void setFlagAutreProp(String flagAutreProp) {
		this.flagAutreProp = flagAutreProp;
	}

	@Column(name = "MT_CHARGE", precision = 18, scale = 3)
	public BigDecimal getMtCharge() {
		return this.mtCharge;
	}

	public void setMtCharge(BigDecimal mtCharge) {
		this.mtCharge = mtCharge;
	}

	@Column(name = "CODE_PROFESSION", length = 4)
	public String getCodeProfession() {
		return this.codeProfession;
	}

	public void setCodeProfession(String codeProfession) {
		this.codeProfession = codeProfession;
	}

	@Column(name = "FLAG_SALARIE", length = 4)
	public String getFlagSalarie() {
		return this.flagSalarie;
	}

	public void setFlagSalarie(String flagSalarie) {
		this.flagSalarie = flagSalarie;
	}

	@Column(name = "MT_SALAIRE", precision = 18, scale = 3)
	public BigDecimal getMtSalaire() {
		return this.mtSalaire;
	}

	public void setMtSalaire(BigDecimal mtSalaire) {
		this.mtSalaire = mtSalaire;
	}

	@Column(name = "MT_AUTRE_REVENU", precision = 18, scale = 3)
	public BigDecimal getMtAutreRevenu() {
		return this.mtAutreRevenu;
	}

	public void setMtAutreRevenu(BigDecimal mtAutreRevenu) {
		this.mtAutreRevenu = mtAutreRevenu;
	}

	@Column(name = "NB_MOIS_ANCIENNETE", precision = 3, scale = 0)
	public Short getNbMoisAnciennete() {
		return this.nbMoisAnciennete;
	}

	public void setNbMoisAnciennete(Short nbMoisAnciennete) {
		this.nbMoisAnciennete = nbMoisAnciennete;
	}

	@Column(name = "CODE_CONTRAT_TRAVAIL", length = 4)
	public String getCodeContratTravail() {
		return this.codeContratTravail;
	}

	public void setCodeContratTravail(String codeContratTravail) {
		this.codeContratTravail = codeContratTravail;
	}

	@Column(name = "SIRET1", length = 3)
	public String getSiret1() {
		return this.siret1;
	}

	public void setSiret1(String siret1) {
		this.siret1 = siret1;
	}

	@Column(name = "SIRET2", length = 3)
	public String getSiret2() {
		return this.siret2;
	}

	public void setSiret2(String siret2) {
		this.siret2 = siret2;
	}

	@Column(name = "SIRET3", length = 3)
	public String getSiret3() {
		return this.siret3;
	}

	public void setSiret3(String siret3) {
		this.siret3 = siret3;
	}

	@Column(name = "SIRET4", length = 5)
	public String getSiret4() {
		return this.siret4;
	}

	public void setSiret4(String siret4) {
		this.siret4 = siret4;
	}

	@Column(name = "RAISON_SOCIALE_1", length = 80)
	public String getRaisonSociale1() {
		return this.raisonSociale1;
	}

	public void setRaisonSociale1(String raisonSociale1) {
		this.raisonSociale1 = raisonSociale1;
	}

	@Column(name = "RAISON_SOCIALE_2", length = 80)
	public String getRaisonSociale2() {
		return this.raisonSociale2;
	}

	public void setRaisonSociale2(String raisonSociale2) {
		this.raisonSociale2 = raisonSociale2;
	}

	@Column(name = "RAISON_SOCIALE_3", length = 80)
	public String getRaisonSociale3() {
		return this.raisonSociale3;
	}

	public void setRaisonSociale3(String raisonSociale3) {
		this.raisonSociale3 = raisonSociale3;
	}

	@Column(name = "DATE_DEB_ACT", precision = 10, scale = 0)
	public Long getDateDebAct() {
		return this.dateDebAct;
	}

	public void setDateDebAct(Long dateDebAct) {
		this.dateDebAct = dateDebAct;
	}

	@Column(name = "DATE_FIN_ACT", precision = 10, scale = 0)
	public Long getDateFinAct() {
		return this.dateFinAct;
	}

	public void setDateFinAct(Long dateFinAct) {
		this.dateFinAct = dateFinAct;
	}

	@Column(name = "CODE_ACTIVITE", length = 5)
	public String getCodeActivite() {
		return this.codeActivite;
	}

	public void setCodeActivite(String codeActivite) {
		this.codeActivite = codeActivite;
	}

	@Column(name = "CODE_CATEGORIE_TIERS", length = 4)
	public String getCodeCategorieTiers() {
		return this.codeCategorieTiers;
	}

	public void setCodeCategorieTiers(String codeCategorieTiers) {
		this.codeCategorieTiers = codeCategorieTiers;
	}

	@Column(name = "CATEGORIE_INSEE", length = 4)
	public String getCategorieInsee() {
		return this.categorieInsee;
	}

	public void setCategorieInsee(String categorieInsee) {
		this.categorieInsee = categorieInsee;
	}

	@Column(name = "MT_CAPITAL", precision = 18, scale = 3)
	public BigDecimal getMtCapital() {
		return this.mtCapital;
	}

	public void setMtCapital(BigDecimal mtCapital) {
		this.mtCapital = mtCapital;
	}

	@Column(name = "NB_EMPLOYE", precision = 6, scale = 0)
	public Integer getNbEmploye() {
		return this.nbEmploye;
	}

	public void setNbEmploye(Integer nbEmploye) {
		this.nbEmploye = nbEmploye;
	}

	@Column(name = "REPRESENTANT", length = 60)
	public String getRepresentant() {
		return this.representant;
	}

	public void setRepresentant(String representant) {
		this.representant = representant;
	}

	@Column(name = "PRENOM_REPRESENTANT", length = 60)
	public String getPrenomRepresentant() {
		return this.prenomRepresentant;
	}

	public void setPrenomRepresentant(String prenomRepresentant) {
		this.prenomRepresentant = prenomRepresentant;
	}

	@Column(name = "EN_QUALITE", length = 30)
	public String getEnQualite() {
		return this.enQualite;
	}

	public void setEnQualite(String enQualite) {
		this.enQualite = enQualite;
	}

	@Column(name = "NO_RC", length = 40)
	public String getNoRc() {
		return this.noRc;
	}

	public void setNoRc(String noRc) {
		this.noRc = noRc;
	}

	@Column(name = "CODE_APE", length = 10)
	public String getCodeApe() {
		return this.codeApe;
	}

	public void setCodeApe(String codeApe) {
		this.codeApe = codeApe;
	}

	@Column(name = "FLAG_PROPRIETAIRE", length = 4)
	public String getFlagProprietaire() {
		return this.flagProprietaire;
	}

	public void setFlagProprietaire(String flagProprietaire) {
		this.flagProprietaire = flagProprietaire;
	}

	@Column(name = "FLAG_PROP_FOND", length = 4)
	public String getFlagPropFond() {
		return this.flagPropFond;
	}

	public void setFlagPropFond(String flagPropFond) {
		this.flagPropFond = flagPropFond;
	}

	@Column(name = "FLAG_TAXE_PRO", length = 4)
	public String getFlagTaxePro() {
		return this.flagTaxePro;
	}

	public void setFlagTaxePro(String flagTaxePro) {
		this.flagTaxePro = flagTaxePro;
	}

	@Column(name = "NIF", length = 20)
	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	@Column(name = "CODE_TERRITORIALITE", length = 4)
	public String getCodeTerritorialite() {
		return this.codeTerritorialite;
	}

	public void setCodeTerritorialite(String codeTerritorialite) {
		this.codeTerritorialite = codeTerritorialite;
	}

	@Column(name = "CODE_REGR_DEC", length = 4)
	public String getCodeRegrDec() {
		return this.codeRegrDec;
	}

	public void setCodeRegrDec(String codeRegrDec) {
		this.codeRegrDec = codeRegrDec;
	}

	@Column(name = "CODE_REGR_ENC", length = 4)
	public String getCodeRegrEnc() {
		return this.codeRegrEnc;
	}

	public void setCodeRegrEnc(String codeRegrEnc) {
		this.codeRegrEnc = codeRegrEnc;
	}

	@Column(name = "TIERS_CONSOLIDATION", length = 10)
	public String getTiersConsolidation() {
		return this.tiersConsolidation;
	}

	public void setTiersConsolidation(String tiersConsolidation) {
		this.tiersConsolidation = tiersConsolidation;
	}

	@Column(name = "CODE_REGIME_FISCAL", length = 4)
	public String getCodeRegimeFiscal() {
		return this.codeRegimeFiscal;
	}

	public void setCodeRegimeFiscal(String codeRegimeFiscal) {
		this.codeRegimeFiscal = codeRegimeFiscal;
	}

	@Column(name = "NOMAFF_TIERS")
	public String getNomaffTiers() {
		return this.nomaffTiers;
	}

	public void setNomaffTiers(String nomaffTiers) {
		this.nomaffTiers = nomaffTiers;
	}

	@Column(name = "MOIS_BILAN", precision = 2, scale = 0)
	public Byte getMoisBilan() {
		return this.moisBilan;
	}

	public void setMoisBilan(Byte moisBilan) {
		this.moisBilan = moisBilan;
	}

	@Column(name = "JOUR_BILAN", precision = 2, scale = 0)
	public Byte getJourBilan() {
		return this.jourBilan;
	}

	public void setJourBilan(Byte jourBilan) {
		this.jourBilan = jourBilan;
	}

	@Column(name = "BANQUE", length = 5)
	public String getBanque() {
		return this.banque;
	}

	public void setBanque(String banque) {
		this.banque = banque;
	}

	@Column(name = "BANQUE_DE_FRANCE", length = 10)
	public String getBanqueDeFrance() {
		return this.banqueDeFrance;
	}

	public void setBanqueDeFrance(String banqueDeFrance) {
		this.banqueDeFrance = banqueDeFrance;
	}

	@Column(name = "GUICHET", length = 5)
	public String getGuichet() {
		return this.guichet;
	}

	public void setGuichet(String guichet) {
		this.guichet = guichet;
	}

	@Column(name = "CODE_DEVISE", length = 4)
	public String getCodeDevise() {
		return this.codeDevise;
	}

	public void setCodeDevise(String codeDevise) {
		this.codeDevise = codeDevise;
	}

	@Column(name = "CODE_GROUPE", length = 4)
	public String getCodeGroupe() {
		return this.codeGroupe;
	}

	public void setCodeGroupe(String codeGroupe) {
		this.codeGroupe = codeGroupe;
	}

	@Column(name = "VILLE_RC", length = 60)
	public String getVilleRc() {
		return this.villeRc;
	}

	public void setVilleRc(String villeRc) {
		this.villeRc = villeRc;
	}

	@Column(name = "TVA_INTRACOMM", length = 15)
	public String getTvaIntracomm() {
		return this.tvaIntracomm;
	}

	public void setTvaIntracomm(String tvaIntracomm) {
		this.tvaIntracomm = tvaIntracomm;
	}

	@Column(name = "CODE_RESEAU", length = 4)
	public String getCodeReseau() {
		return this.codeReseau;
	}

	public void setCodeReseau(String codeReseau) {
		this.codeReseau = codeReseau;
	}

	@Column(name = "CODE_REGION", length = 4)
	public String getCodeRegion() {
		return this.codeRegion;
	}

	public void setCodeRegion(String codeRegion) {
		this.codeRegion = codeRegion;
	}

	@Column(name = "TELEPHONE_CHC", length = 30)
	public String getTelephoneChc() {
		return this.telephoneChc;
	}

	public void setTelephoneChc(String telephoneChc) {
		this.telephoneChc = telephoneChc;
	}

	@Column(name = "DATE_CONTACT", precision = 10, scale = 0)
	public Long getDateContact() {
		return this.dateContact;
	}

	public void setDateContact(Long dateContact) {
		this.dateContact = dateContact;
	}

	@Column(name = "CODE_BANQUE_INGNL", precision = 8, scale = 0)
	public Integer getCodeBanqueIngnl() {
		return this.codeBanqueIngnl;
	}

	public void setCodeBanqueIngnl(Integer codeBanqueIngnl) {
		this.codeBanqueIngnl = codeBanqueIngnl;
	}

	@Column(name = "TIERS_AGENCE", length = 10)
	public String getTiersAgence() {
		return this.tiersAgence;
	}

	public void setTiersAgence(String tiersAgence) {
		this.tiersAgence = tiersAgence;
	}

	@Column(name = "TIERS_ACCM", length = 10)
	public String getTiersAccm() {
		return this.tiersAccm;
	}

	public void setTiersAccm(String tiersAccm) {
		this.tiersAccm = tiersAccm;
	}

	@Column(name = "CODE_BIK", length = 10)
	public String getCodeBik() {
		return this.codeBik;
	}

	public void setCodeBik(String codeBik) {
		this.codeBik = codeBik;
	}

	@Column(name = "REFERENCE_EXTERNE", length = 30)
	public String getReferenceExterne() {
		return this.referenceExterne;
	}

	public void setReferenceExterne(String referenceExterne) {
		this.referenceExterne = referenceExterne;
	}

	@Column(name = "CODE_NBREMP", length = 10)
	public String getCodeNbremp() {
		return this.codeNbremp;
	}

	public void setCodeNbremp(String codeNbremp) {
		this.codeNbremp = codeNbremp;
	}

	@Column(name = "CODE_STATUT_IMPOSE", length = 4)
	public String getCodeStatutImpose() {
		return this.codeStatutImpose;
	}

	public void setCodeStatutImpose(String codeStatutImpose) {
		this.codeStatutImpose = codeStatutImpose;
	}

	@Column(name = "COTATION_OFFICIELLE", length = 4)
	public String getCotationOfficielle() {
		return this.cotationOfficielle;
	}

	public void setCotationOfficielle(String cotationOfficielle) {
		this.cotationOfficielle = cotationOfficielle;
	}

	@Column(name = "IDENTIFIANT_BDF", length = 13)
	public String getIdentifiantBdf() {
		return this.identifiantBdf;
	}

	public void setIdentifiantBdf(String identifiantBdf) {
		this.identifiantBdf = identifiantBdf;
	}

	@Column(name = "FLAG_IDENT_PRINCIPAL", length = 4)
	public String getFlagIdentPrincipal() {
		return this.flagIdentPrincipal;
	}

	public void setFlagIdentPrincipal(String flagIdentPrincipal) {
		this.flagIdentPrincipal = flagIdentPrincipal;
	}

	@Column(name = "CODE_TYPE_REVENU", length = 4)
	public String getCodeTypeRevenu() {
		return this.codeTypeRevenu;
	}

	public void setCodeTypeRevenu(String codeTypeRevenu) {
		this.codeTypeRevenu = codeTypeRevenu;
	}

	@Column(name = "MONTANT_REVENU", precision = 18, scale = 3)
	public BigDecimal getMontantRevenu() {
		return this.montantRevenu;
	}

	public void setMontantRevenu(BigDecimal montantRevenu) {
		this.montantRevenu = montantRevenu;
	}

	@Column(name = "DATE_PRESENCE", precision = 10, scale = 0)
	public Long getDatePresence() {
		return this.datePresence;
	}

	public void setDatePresence(Long datePresence) {
		this.datePresence = datePresence;
	}

	@Column(name = "FLAG_REVERS_TVA", length = 4)
	public String getFlagReversTva() {
		return this.flagReversTva;
	}

	public void setFlagReversTva(String flagReversTva) {
		this.flagReversTva = flagReversTva;
	}

	@Column(name = "CODE_NACE_TIERS", length = 5)
	public String getCodeNaceTiers() {
		return this.codeNaceTiers;
	}

	public void setCodeNaceTiers(String codeNaceTiers) {
		this.codeNaceTiers = codeNaceTiers;
	}

	@Column(name = "PREFIX_TIERS", length = 10)
	public String getPrefixTiers() {
		return this.prefixTiers;
	}

	public void setPrefixTiers(String prefixTiers) {
		this.prefixTiers = prefixTiers;
	}

	@Column(name = "TITLE_TIERS", length = 20)
	public String getTitleTiers() {
		return this.titleTiers;
	}

	public void setTitleTiers(String titleTiers) {
		this.titleTiers = titleTiers;
	}

	@Column(name = "NIP_NUMBER", length = 20)
	public String getNipNumber() {
		return this.nipNumber;
	}

	public void setNipNumber(String nipNumber) {
		this.nipNumber = nipNumber;
	}

	@Column(name = "REGON_NUMBER", precision = 20, scale = 0)
	public BigDecimal getRegonNumber() {
		return this.regonNumber;
	}

	public void setRegonNumber(BigDecimal regonNumber) {
		this.regonNumber = regonNumber;
	}

	@Column(name = "AUTRES_CHARGES", precision = 18, scale = 3)
	public BigDecimal getAutresCharges() {
		return this.autresCharges;
	}

	public void setAutresCharges(BigDecimal autresCharges) {
		this.autresCharges = autresCharges;
	}

	@Column(name = "CODE_CLASSIF_MARCHE", length = 4)
	public String getCodeClassifMarche() {
		return this.codeClassifMarche;
	}

	public void setCodeClassifMarche(String codeClassifMarche) {
		this.codeClassifMarche = codeClassifMarche;
	}

	@Column(name = "CODE_CLASSIF_SEGMENT", length = 4)
	public String getCodeClassifSegment() {
		return this.codeClassifSegment;
	}

	public void setCodeClassifSegment(String codeClassifSegment) {
		this.codeClassifSegment = codeClassifSegment;
	}

	@Column(name = "FLAG_RECUP_TVA", length = 4)
	public String getFlagRecupTva() {
		return this.flagRecupTva;
	}

	public void setFlagRecupTva(String flagRecupTva) {
		this.flagRecupTva = flagRecupTva;
	}

	@Column(name = "DATE_ENTREE_EMPLOI", precision = 10, scale = 0)
	public Long getDateEntreeEmploi() {
		return this.dateEntreeEmploi;
	}

	public void setDateEntreeEmploi(Long dateEntreeEmploi) {
		this.dateEntreeEmploi = dateEntreeEmploi;
	}

	@Column(name = "DATE_ENTREE_LGT", precision = 10, scale = 0)
	public Long getDateEntreeLgt() {
		return this.dateEntreeLgt;
	}

	public void setDateEntreeLgt(Long dateEntreeLgt) {
		this.dateEntreeLgt = dateEntreeLgt;
	}

	@Column(name = "FLAG_CONVERSION", length = 1)
	public String getFlagConversion() {
		return this.flagConversion;
	}

	public void setFlagConversion(String flagConversion) {
		this.flagConversion = flagConversion;
	}

	@Column(name = "INDICATEUR_CONVERSION", length = 1)
	public String getIndicateurConversion() {
		return this.indicateurConversion;
	}

	public void setIndicateurConversion(String indicateurConversion) {
		this.indicateurConversion = indicateurConversion;
	}

	@Column(name = "NUM_AVT_EURO", precision = 11, scale = 6)
	public BigDecimal getNumAvtEuro() {
		return this.numAvtEuro;
	}

	public void setNumAvtEuro(BigDecimal numAvtEuro) {
		this.numAvtEuro = numAvtEuro;
	}

	@Column(name = "DENO_AVT_EURO", precision = 11, scale = 6)
	public BigDecimal getDenoAvtEuro() {
		return this.denoAvtEuro;
	}

	public void setDenoAvtEuro(BigDecimal denoAvtEuro) {
		this.denoAvtEuro = denoAvtEuro;
	}

	@Column(name = "NOMEDT_TIERS1")
	public String getNomedtTiers1() {
		return this.nomedtTiers1;
	}

	public void setNomedtTiers1(String nomedtTiers1) {
		this.nomedtTiers1 = nomedtTiers1;
	}

	@Column(name = "NOMEDT_TIERS2")
	public String getNomedtTiers2() {
		return this.nomedtTiers2;
	}

	public void setNomedtTiers2(String nomedtTiers2) {
		this.nomedtTiers2 = nomedtTiers2;
	}

	@Column(name = "NOMEDT_TIERS3")
	public String getNomedtTiers3() {
		return this.nomedtTiers3;
	}

	public void setNomedtTiers3(String nomedtTiers3) {
		this.nomedtTiers3 = nomedtTiers3;
	}

	@Column(name = "MT_REVENUS_CONJOINT", precision = 18, scale = 3)
	public BigDecimal getMtRevenusConjoint() {
		return this.mtRevenusConjoint;
	}

	public void setMtRevenusConjoint(BigDecimal mtRevenusConjoint) {
		this.mtRevenusConjoint = mtRevenusConjoint;
	}

	@Column(name = "CODE_INSEE_NAISS", length = 10)
	public String getCodeInseeNaiss() {
		return this.codeInseeNaiss;
	}

	public void setCodeInseeNaiss(String codeInseeNaiss) {
		this.codeInseeNaiss = codeInseeNaiss;
	}

	@Column(name = "DATE_JUGEMENT", precision = 10, scale = 0)
	public Long getDateJugement() {
		return this.dateJugement;
	}

	public void setDateJugement(Long dateJugement) {
		this.dateJugement = dateJugement;
	}

	@Column(name = "NOMEDT_TIERS4")
	public String getNomedtTiers4() {
		return this.nomedtTiers4;
	}

	public void setNomedtTiers4(String nomedtTiers4) {
		this.nomedtTiers4 = nomedtTiers4;
	}

	@Column(name = "NOMEDT_TIERS5")
	public String getNomedtTiers5() {
		return this.nomedtTiers5;
	}

	public void setNomedtTiers5(String nomedtTiers5) {
		this.nomedtTiers5 = nomedtTiers5;
	}

	@Column(name = "NOMEDT_TIERS6")
	public String getNomedtTiers6() {
		return this.nomedtTiers6;
	}

	public void setNomedtTiers6(String nomedtTiers6) {
		this.nomedtTiers6 = nomedtTiers6;
	}

	@Column(name = "NOMEDT_TIERS7")
	public String getNomedtTiers7() {
		return this.nomedtTiers7;
	}

	public void setNomedtTiers7(String nomedtTiers7) {
		this.nomedtTiers7 = nomedtTiers7;
	}

	@Column(name = "NOMEDT_TIERS8")
	public String getNomedtTiers8() {
		return this.nomedtTiers8;
	}

	public void setNomedtTiers8(String nomedtTiers8) {
		this.nomedtTiers8 = nomedtTiers8;
	}

	@Column(name = "NOMEDT_TIERS9")
	public String getNomedtTiers9() {
		return this.nomedtTiers9;
	}

	public void setNomedtTiers9(String nomedtTiers9) {
		this.nomedtTiers9 = nomedtTiers9;
	}

	@Column(name = "NOMEDT_TIERS10")
	public String getNomedtTiers10() {
		return this.nomedtTiers10;
	}

	public void setNomedtTiers10(String nomedtTiers10) {
		this.nomedtTiers10 = nomedtTiers10;
	}

	@Column(name = "NOM_MAJUSCULE")
	public String getNomMajuscule() {
		return this.nomMajuscule;
	}

	public void setNomMajuscule(String nomMajuscule) {
		this.nomMajuscule = nomMajuscule;
	}

	@Column(name = "COD_ACT_BAM", length = 4)
	public String getCodActBam() {
		return this.codActBam;
	}

	public void setCodActBam(String codActBam) {
		this.codActBam = codActBam;
	}

	@Column(name = "ERREUR_DEB_BAM", length = 7)
	public String getErreurDebBam() {
		return this.erreurDebBam;
	}

	public void setErreurDebBam(String erreurDebBam) {
		this.erreurDebBam = erreurDebBam;
	}

	@Column(name = "ERREUR_MAJB_BAM", length = 7)
	public String getErreurMajbBam() {
		return this.erreurMajbBam;
	}

	public void setErreurMajbBam(String erreurMajbBam) {
		this.erreurMajbBam = erreurMajbBam;
	}

	@Column(name = "NUM_RISQUE_BAM", length = 7)
	public String getNumRisqueBam() {
		return this.numRisqueBam;
	}

	public void setNumRisqueBam(String numRisqueBam) {
		this.numRisqueBam = numRisqueBam;
	}

	@Column(name = "NO_GREF_EXPERIAN", length = 30)
	public String getNoGrefExperian() {
		return this.noGrefExperian;
	}

	public void setNoGrefExperian(String noGrefExperian) {
		this.noGrefExperian = noGrefExperian;
	}

	@Column(name = "RECH_TIERS1", length = 60)
	public String getRechTiers1() {
		return this.rechTiers1;
	}

	public void setRechTiers1(String rechTiers1) {
		this.rechTiers1 = rechTiers1;
	}

	@Column(name = "RECH_TIERS2", length = 60)
	public String getRechTiers2() {
		return this.rechTiers2;
	}

	public void setRechTiers2(String rechTiers2) {
		this.rechTiers2 = rechTiers2;
	}

	@Column(name = "CODE_VIP", length = 4)
	public String getCodeVip() {
		return this.codeVip;
	}

	public void setCodeVip(String codeVip) {
		this.codeVip = codeVip;
	}

	@Column(name = "CODE_SAE", length = 4)
	public String getCodeSae() {
		return this.codeSae;
	}

	public void setCodeSae(String codeSae) {
		this.codeSae = codeSae;
	}

	@Column(name = "CODE_RAE", length = 4)
	public String getCodeRae() {
		return this.codeRae;
	}

	public void setCodeRae(String codeRae) {
		this.codeRae = codeRae;
	}

	@Column(name = "CODE_SEXE", length = 4)
	public String getCodeSexe() {
		return this.codeSexe;
	}

	public void setCodeSexe(String codeSexe) {
		this.codeSexe = codeSexe;
	}

	@Column(name = "ID_GROUPE_SGT", precision = 10, scale = 0)
	public Long getIdGroupeSgt() {
		return this.idGroupeSgt;
	}

	public void setIdGroupeSgt(Long idGroupeSgt) {
		this.idGroupeSgt = idGroupeSgt;
	}

	@Column(name = "CODE_MODE_CREATION", length = 4)
	public String getCodeModeCreation() {
		return this.codeModeCreation;
	}

	public void setCodeModeCreation(String codeModeCreation) {
		this.codeModeCreation = codeModeCreation;
	}

	@Column(name = "CODE_CONSOLIDATION", length = 4)
	public String getCodeConsolidation() {
		return this.codeConsolidation;
	}

	public void setCodeConsolidation(String codeConsolidation) {
		this.codeConsolidation = codeConsolidation;
	}

	@Column(name = "CODE_STATUT", length = 4)
	public String getCodeStatut() {
		return this.codeStatut;
	}

	public void setCodeStatut(String codeStatut) {
		this.codeStatut = codeStatut;
	}

	@Column(name = "ID_MASQUAGE", nullable = false, precision = 10, scale = 0)
	public long getIdMasquage() {
		return this.idMasquage;
	}

	public void setIdMasquage(long idMasquage) {
		this.idMasquage = idMasquage;
	}

	@Column(name = "NUMERO_NATIONAL_ID", length = 20)
	public String getNumeroNationalId() {
		return this.numeroNationalId;
	}

	public void setNumeroNationalId(String numeroNationalId) {
		this.numeroNationalId = numeroNationalId;
	}

}
